version: '3'

services:
  saxon:
    build:
      context: .
      dockerfile: .docker/saxon/Dockerfile
    volumes:
      - .:/aggregator_mdx
  xspec:
    build:
      context: .
      dockerfile: .docker/test/Dockerfile
    volumes:
      - .:/aggregator_mdx
