<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:dcterms="http://purl.org/dc/terms/"
    xmlns:dpla="http://dp.la/about/map/"
    xmlns:padig="http://padigital.org/ns"
    xmlns:edm="http://www.europeana.eu/schemas/edm/"
    xmlns:oclcdc="http://worldcat.org/xmlschemas/oclcdc-1.0/"
    xmlns:oclcterms="http://purl.org/oclc/terms/"
    xmlns:oai="http://www.openarchives.org/OAI/2.0/"
    xmlns:oai_dc='http://www.openarchives.org/OAI/2.0/oai_dc/'
    xmlns:oclc="http://purl.org/oclc/terms/"
    xmlns:oai_qdc="http://worldcat.org/xmlschemas/qdc-1.0/"
    xmlns:schema="http://schema.org"
    xmlns:svcs="http://rdfs.org/sioc/services"
    version="2.0">

    <!-- POWER photos and docs collecton name lookup -->
    <xsl:param name="powerSetSpecList">
        <padig:set string="Abington Township Public Library - Abington High School Yearbooks">papd_paflp-ahsyc</padig:set>
        <padig:set string="Albright College - Central Pennsylvania College Photos">papd_cpaphoto</padig:set>
        <padig:set string="Albright College - Evangelical Church Historic Lantern Slides">papd_churchslide</padig:set>
        <padig:set string="Albright College - Myerstown Photos">papd_myrsphoto</padig:set>
        <padig:set string="Albright College - Schuylkill Seminary Photos">papd_sklsemphoto</padig:set>
        <padig:set string="Albright College - The Seminary Guard Newspaper">papd_aalbcsemgu</padig:set>
        <padig:set string="Albright College - The Seminary Guard Newspaper">papd_aalbcsemgu_96</padig:set>
        <padig:set string="Albright College - The Seminary Guard Newspaper">papd_aalbcsemgu_96_2_4</padig:set>
        <padig:set string="Altoona Area Public Library - Altoona Area School District History">papd_palap-aasdh</padig:set>
        <padig:set string="Altoona Area Public Library - Architecture: Practical and Theoretical">papd_palap-apt</padig:set>
        <padig:set string="Altoona Area Public Library - Blair County Oral Histories">papd_palap-bcoh</padig:set>
        <padig:set string="Altoona Area Public Library - History Photographs">papd_palap-hp</padig:set>
        <padig:set string="Bedford County Library - Winona Garbrick">papd_pbecf-wg</padig:set>
        <padig:set string="Bellwood-Antis Public Library - Bellwood Bulletin Newspaper">papd_pbapl-bb</padig:set>
        <padig:set string="Boyertown Area Senior High School - Boyertown School News">papd_kboyh-bsn</padig:set>
        <padig:set string="Cambria County Library - Johnstown, PA History Books">papd_pcccp-books</padig:set>
        <padig:set string="Cambria County Library - Johnstown, PA Postcards">papd_pcccp-post</padig:set>
        <padig:set string="Carnegie Library of Pittsburgh - American Marketplace">papd_pcalo-amc</padig:set>
        <padig:set string="Carnegie Library of Pittsburgh - Pittsburgh Iron &amp; Steel Heritage">papd_pcalo-ishc</padig:set>
        <padig:set string="Carnegie Library of Pittsburgh - The Builder">papd_pcalo-build2</padig:set>
        <padig:set string="Centre County Library &amp; Historical Museum - Bellefonte Governors' Papers">papd_pcecl-bgp</padig:set>
        <padig:set string="Chester County Library &amp; District - Northern Chester County Historic Photographs">papd_pcccl-ncchp</padig:set>
        <padig:set string="Clarion Free Library - Mary Hamilton Holiday Cards">papd_pclfl-mhhc</padig:set>
        <padig:set string="Clarion Free Library - World War I">papd_pclfl-wwi</padig:set>
        <padig:set string="Crawford County Federated Library System - Meadville Local History">papd_pmeplmlhc</padig:set>
        <padig:set string="Elizabethtown College - Anna V. Blough Missionary Letters and Diaries from China">papd_aeliz-lttrs</padig:set>
        <padig:set string="Elizabethtown College - Church of the Brethren Photographs">papd_aeliz-cbpc</padig:set>
        <padig:set string="Elizabethtown College - Historic Images">papd_aeliz-hi</padig:set>
        <padig:set string="Elizabethtown College - Peace Pamphlets">papd_aeliz-pp</padig:set>
        <padig:set string="Erie County Public Library - Erie County Yearbooks">papd_percp-ecy</padig:set>
        <padig:set string="Friends Central School - Early Photographs">papd_kfces-photo</padig:set>
        <padig:set string="Geneva College - Postcards">papd_agene-pcard</padig:set>
        <padig:set string="German Society of Pennsylvania - Women's Auxiliary of the German Society of Pennsylvania">papd_sgsop-wagsp</padig:set>
        <padig:set string="Heinz History Center - Buhl Foundation Photographs">papd_shswp-bfp</padig:set>
        <padig:set string="James V. Brown Library - Lycoming County Digital Photo Archive">papd_pjvbl-archi</padig:set>
        <padig:set string="Keystone College - Christy Mathewson">papd_akeyscmath</padig:set>
        <padig:set string="Kiski School - Digital Archive">papd_kthks-tksc</padig:set>
        <padig:set string="Kiski School - Digital Archive">papd_kthks-tksc_266</padig:set>
        <padig:set string="Kiski School - Digital Archive">papd_kthks-tksc_266_2_1</padig:set>
        <padig:set string="Lancaster Public Library - Yearbooks">papd_placl-ybook</padig:set>
        <padig:set string="LancasterHistory - City Directories 1843-1900">papd_slchs-cd01</padig:set>
        <padig:set string="Le Cordon Bleu Inst of Culinary Arts - Amer. Culinary Fed., Pittsburgh Chapter">papd_apacl-acfpc</padig:set>
        <padig:set string="Lock Haven University - 1877-2008">papd_alhupviscro</padig:set>
        <padig:set string="Lycoming College - Alumni Magazine of Lycoming College">papd_alycc-almag</padig:set>
        <padig:set string="Lycoming College - Lycoming College">papd_lyc-4</padig:set>
        <padig:set string="Lycoming College - Lycoming College Campus - Past and Present">papd_lyc-5</padig:set>
        <padig:set string="Lycoming College - Lycoming County Women's History">papd_alycc-wmhis</padig:set>
        <padig:set string="Lycoming College - Lycoming County Women's History">papd_alycc-wmhis_6567</padig:set>
        <padig:set string="Lycoming College - Lycoming County Women's History">papd_alycc-wmhis_7146</padig:set>
        <padig:set string="Lycoming College - Lycoming County Women's History">papd_alycc-wmhis_7510</padig:set>
        <padig:set string="Lycoming College - Moving Images of Lycoming College">papd_alycc-mvimg</padig:set>
        <padig:set string="Lycoming College - Student Newspapers, 1856-present">papd_lycnews</padig:set>
        <padig:set string="Lycoming College - Voices of Lycoming">papd_alycc-voice</padig:set>
        <padig:set string="Lycoming College - Williamsport Dickinson Seminary Junior College and College Preparatory School">papd_lyc-2</padig:set>
        <padig:set string="Lycoming College - Williamsport Dickinson Seminary of Lycoming College">papd_lyc-1</padig:set>
        <padig:set string="Lycoming College - Yearbooks of Lycoming College and Dickinson Seminary">papd_alycc-ybook</padig:set>
        <padig:set string="Matthews Public Library - Fredericksburg, Pennsylvania Historic Images">papd_plecl-fphi</padig:set>
        <padig:set string="McBride Memorial Library - Berwick High School Yearbooks">papd_pbrpl-bhsyb</padig:set>
        <padig:set string="Mengle Memorial Library - The Punxsutawney Spirit Newspaper">papd_pmeml-psprt</padig:set>
        <padig:set string="Meyersdale Public Library - Photographs">papd_pmeye-photo</padig:set>
        <padig:set string="Monroeville Public Library - Allegheny County Yearbooks">papd_pmonr-acy</padig:set>
        <padig:set string="Montgomery County Community College - Betzwood Studios">papd_amccc-betz</padig:set>
        <padig:set string="New Castle Public Library - Cascade Park">papd_pncpl-cp</padig:set>
        <padig:set string="New Castle Public Library - New Castle Directories 1872-1899">papd_pncpl-cdr01</padig:set>
        <padig:set string="New Castle Public Library - New Castle Directories 1900-1910">papd_pncpl-cdr02</padig:set>
        <padig:set string="New Castle Public Library - New Castle Directories 1911-1918">papd_pncpl-cdr03</padig:set>
        <padig:set string="New Castle Public Library - New Castle Directories 1921-1928">papd_pncpl-cdr04</padig:set>
        <padig:set string="New Castle Public Library - New Castle High School Yearbooks">papd_pncpl-nchsy</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - American Association of University Women - Johnstown Branch">papd_acacc-aauwjb</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - Bailey Collection">papd_acacc-bailey</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - Beaverdale Collection">papd_acacc-bdale</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - Cambria City Church Project">papd_acacc-cccp</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - Cambria Civil War 150">papd_acacc-cw</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - Cambria Memory Project">papd_acacc-memor</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - Cresson Sanatorium">papd_acacc-cs</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - Johnstown Area Fire Department Collection">papd_acacc-jafd</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - Northern Cambria Collection">papd_acacc-noca</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - The Johnstown Flood of 1889">papd_acacc-jtf</padig:set>
        <padig:set string="Pennsylvania Horticultural Society - Philadelphia Flower Show">papd_spahs-pfsc</padig:set>
        <padig:set string="Pennsylvania Horticultural Society - Philadelphia Garden Photographs, 1900-1940: 1. Garden Club of Philadelphia">papd_spahs-pgpgcp</padig:set>
        <padig:set string="Pennsylvania Horticultural Society - Philadelphia Garden Photographs, 1900-1940: 2. John C. Wister Collection">papd_spahs-pgp1940</padig:set>
        <padig:set string="Pennsylvania Horticultural Society - Philadelphia Garden Photographs, 1900-1940: 3. PHS Collection Portfolios">papd_spahs-pgpphscp</padig:set>
        <padig:set string="Pennsylvania Horticultural Society - PHS Archives Digital Image Collection">papd_spahs-padic</padig:set>
        <padig:set string="Pennsylvania School for the Deaf - Mount Airy Campus">papd_kpsfd-mac</padig:set>
        <padig:set string="Pottsville Free Public Library - Schuylkill County History">papd_ppofp-sch</padig:set>
        <padig:set string="Pottsville Free Public Library - Schuylkill County Photographs">papd_ppofp-scp</padig:set>
        <padig:set string="Reading Area Community College - The Schuylkill Navigation System">papd_aracc-sns</padig:set>
        <padig:set string="Reading Public Library - Berks County Postcards">papd_prepl-brcpc</padig:set>
        <padig:set string="Reading Public Library - Berks County Yearbooks">papd_prepl-brcyb</padig:set>
        <padig:set string="Saint Francis University - Student Newspapers 1927-2006">papd_astfr-ysnmc</padig:set>
        <padig:set string="Saint Francis University Yearbooks 1942-2016">papd_astfr-yearbks</padig:set>
        <padig:set string="Schwenkfelder Library &amp; Heritage Center - Rosina Heydrich's Midwifery Manual and Ledger, 1770-1819">papd_sslch-sdsa</padig:set>
        <padig:set string="Scranton Public Library - Celebrating Our Towns: Lackawanna Co. Centennial Books and Community Histories">papd_pscrl-cot</padig:set>
        <padig:set string="Scranton Public Library - Century Club of Scranton">papd_pscrl-ccos</padig:set>
        <padig:set string="Scranton Public Library - Community and Church Cookbooks from Northeastern PA">papd_pscrl-cccfnepa</padig:set>
        <padig:set string="Scranton Public Library - Friends of the Scranton Public Library Poetry Series">papd_pscrl-fsplps</padig:set>
        <padig:set string="Scranton Public Library - From Lace Makers to Coal Miners: Life in the Lackawanna Valley 1866-1920">papd_pscrl-flmtcm</padig:set>
        <padig:set string="Scranton Public Library - History of the Scranton Public Library">papd_pscrl-hspl</padig:set>
        <padig:set string="Scranton Public Library - Natural Disasters in NePA--Hurricane Diane">papd_pscrl-ndnepa</padig:set>
        <padig:set string="Scranton Public Library - Nay Aug Amusement Park--The Strohl Collection">papd_pscrl-naap</padig:set>
        <padig:set string="Scranton Public Library - Out of the Wilderness: The Industrialization and Development of the the Scranton Area 1850-1865">papd_pscrl-ootw</padig:set>
        <padig:set string="Scranton Public Library - Scranton Christmas Windows">papd_pscrl-scw</padig:set>
        <padig:set string="Scranton Public Library - The Story of the Community Medical Center">papd_pscrl-socmc</padig:set>
        <padig:set string="Sewickley Public Library - The Sewickley Herald Newspaper 1903-">papd_psepl-sh</padig:set>
        <padig:set string="St. Marys Public Library - The St. Marys Daily Press">papd_pstmp-smdp</padig:set>
        <padig:set string="State Library of Pennsylvania - County Histories">papd_sstlp-ch</padig:set>
        <padig:set string="State Library of Pennsylvania - Elizabethville Echo Newspaper">papd_sstlp-elec</padig:set>
        <padig:set string="State Library of Pennsylvania - Elk Enterprise Newspaper">papd_sstlp-elkent</padig:set>
        <padig:set string="State Library of Pennsylvania - Fort Necessity">papd_sstlp-ftnes</padig:set>
        <padig:set string="State Library of Pennsylvania - German Language Collection">papd_sstlp-germanlang</padig:set>
        <padig:set string="State Library of Pennsylvania - Governor's Mansion">papd_sstlp-gvman</padig:set>
        <padig:set string="State Library of Pennsylvania - Harrisburg Whig State Journal Newspaper">papd_sstlp-harwhig</padig:set>
        <padig:set string="State Library of Pennsylvania - History of State Library of Pennsylvania">papd_sstlp-slph</padig:set>
        <padig:set string="State Library of Pennsylvania - Lancaster Intelligencer Newspaper">papd_sstlp-lancintel</padig:set>
        <padig:set string="State Library of Pennsylvania - Lebanon Advertiser Newspaper">papd_sstlp-lead</padig:set>
        <padig:set string="State Library of Pennsylvania - Lewistown Republican Newspaper">papd_sstlp-lewrep</padig:set>
        <padig:set string="State Library of Pennsylvania - Mapleton Advertiser Newspaper">papd_sstlp-maad</padig:set>
        <padig:set string="State Library of Pennsylvania - Mapleton Item Newspaper">papd_sstlp-mait</padig:set>
        <padig:set string="State Library of Pennsylvania - Marietta Advocate and Farmers and Mechanics Intelligencer Newspaper">papd_sstlp-maradv</padig:set>
        <padig:set string="State Library of Pennsylvania - Marietta Pioneer Newspaper">papd_sstlp-marpion</padig:set>
        <padig:set string="State Library of Pennsylvania - Marietta Register Newspaper">papd_sstlp-marreg</padig:set>
        <padig:set string="State Library of Pennsylvania - Mariettian Newspaper">papd_sstlp-mariettian</padig:set>
        <padig:set string="State Library of Pennsylvania - Mercer Dispatch Newspaper">papd_sstlp-medi</padig:set>
        <padig:set string="State Library of Pennsylvania - Mt. Pleasant Journal Newspaper">papd_sstlp-mtpleasjl</padig:set>
        <padig:set string="State Library of Pennsylvania - Pennsylvania Bulletin">papd_sstlp-pab</padig:set>
        <padig:set string="State Library of Pennsylvania - Pennsylvania Conservation and Science">papd_sstlp-cas</padig:set>
        <padig:set string="State Library of Pennsylvania - Pennsylvania Education">papd_sstlp-pe</padig:set>
        <padig:set string="State Library of Pennsylvania - Pennsylvania Native Americans">papd_sstlp-panat</padig:set>
        <padig:set string="State Library of Pennsylvania - Pennsylvania State Agency Documents">papd_slppadocs</padig:set>
        <padig:set string="State Library of Pennsylvania - Pennsylvania Transportation">papd_sstlp-pt</padig:set>
        <padig:set string="State Library of Pennsylvania - Philadelphia Christian Observer Newspaper">papd_sstlp-phchobs</padig:set>
        <padig:set string="State Library of Pennsylvania - Philadelphia Daily Chronicle Newspaper">papd_sstlp-phdchron</padig:set>
        <padig:set string="State Library of Pennsylvania - Philadelphia Sun Newspaper">papd_sstlp-philasun</padig:set>
        <padig:set string="State Library of Pennsylvania - Philadelphia Sunday-school Times Newspaper">papd_sstlp-philsunsch</padig:set>
        <padig:set string="State Library of Pennsylvania - Potter County Journal Newspaper">papd_sstlp-pottercojl</padig:set>
        <padig:set string="State Library of Pennsylvania - Regimental Histories">papd_sstlp-reg</padig:set>
        <padig:set string="State Library of Pennsylvania - State's Advocate Newspaper">papd_sstlp-statesadv</padig:set>
        <padig:set string="State Library of Pennsylvania - The Colonization Herald and General Register Newspaper">papd_sstlp-colher</padig:set>
        <padig:set string="State Library of Pennsylvania - Titusville Courier Newspaper">papd_sstlp-tico</padig:set>
        <padig:set string="State Library of Pennsylvania - Titusville Herald Newspaper">papd_sstlp-tihe</padig:set>
        <padig:set string="State Library of Pennsylvania - Wilkes-Barre Daily Newspaper">papd_sstlp-wbda</padig:set>
        <padig:set string="State Library of Pennsylvania - World War I">papd_sstlp-wwi</padig:set>
        <padig:set string="Susquehanna University - 1858 to 1894">papd_asvbw150</padig:set>
        <padig:set string="Susquehanna University - 1895 to 1939">papd_asvbw95-39</padig:set>
        <padig:set string="Susquehanna University - 1940 to 1949">papd_asvbw40-49</padig:set>
        <padig:set string="Susquehanna University - 1950 to 1959">papd_asvbw50-59</padig:set>
        <padig:set string="Susquehanna University - 1960 to 1969">papd_asvbw60-69</padig:set>
        <padig:set string="Susquehanna University - 1970 to 1979">papd_asvbw70-79</padig:set>
        <padig:set string="Susquehanna University - 1980 to 1989">papd_asvbw80-89</padig:set>
        <padig:set string="Susquehanna University - 1990 to 1999">papd_asvbw90-99</padig:set>
        <padig:set string="Susquehanna University - 2000 to 2009">papd_asvbw00-09</padig:set>
        <padig:set string="Swarthmore Public Library - History of the Swarthmore Public Library Association">papd_pswpl-splh</padig:set>
        <padig:set string="The Baldwin School - Blazers, Uniforms, Gowns">papd_kthbs-bug</padig:set>
        <padig:set string="The Baldwin School - Photos and Documents">papd_kthbs-arch</padig:set>
        <padig:set string="The Baldwin School - The Hourglass">papd_kthbs-hg</padig:set>
        <padig:set string="Ulysses Library Association - Phil Bennett Collection">papd_pulpl-pbc</padig:set>
        <padig:set string="Ulysses Library Association - Ulysses History">papd_pulpl-uh</padig:set>
        <padig:set string="United Lutheran Seminary Philadelphia - In Her Own Right: the Lutheran Deaconess Movement in the United States">papd_aulsp-ihorldm</padig:set>
        <padig:set string="United Lutheran Seminary Philadelphia - In Her Own Right: Women's Missionary Societies of the Lutheran Church">papd_aulsp-ihorwmslc</padig:set>
        <padig:set string="Warren Library Association - Historic Flood Control (1943)">papd_pwala-hstfl</padig:set>
        <padig:set string="Warren Library Association - Historic Photographs">papd_pwala-hstph</padig:set>
        <padig:set string="Warren Library Association - The Carnival, First Presbyterian Church, 1899">papd_pwala-tcfpc</padig:set>
        <padig:set string="Williamson College of the Trades - Isaiah Van Sant Williamson History">papd_awsmt-ivswh</padig:set>
        <padig:set string="Williamson College of the Trades - Williamson Trade School History">papd_awsmt-wtsh</padig:set>

    <!-- POWER state archives collecton name lookup -->
        <padig:set string="2nd Geological Survey (PA) Accounts of Board Commissioners, 1875-1877">psa_gsabc</padig:set>
        <padig:set string="2nd Geological Survey (PA) County Geological Maps of the Board of Commissioners">psa_gscgmbc</padig:set>
        <padig:set string="2nd Geological Survey (PA) Diary of Charles Ashburner Board of Commissioners, 1876">psa_gsdcaabc</padig:set>
        <padig:set string="2nd Geological Survey (PA) Field Expense Act Book Charles Ashburner, A W Sheafer">psa_gsfeabca</padig:set>
        <padig:set string="2nd Geological Survey (PA) Field Note Books of the Board of Commissioners, 1875">psa_gsfnbbc</padig:set>
        <padig:set string="2nd Geological Survey (PA) General Correspondence of the Board of Commissioners">psa_gsgcbc</padig:set>
        <padig:set string="2nd Geological Survey (PA) Minutes of the Board of Commissioners, 1874-1896">psa_gsmbc</padig:set>
        <padig:set string="Account of the United States to the State of Pennsylvania (PA), 1775-1788">psa_aussppa</padig:set>
        <padig:set string="Administrative and Biennial Reports, 1915-1969">psa_abr1915</padig:set>
        <padig:set string="Admission and Discharge Books (PA), 1844-1888">psa_aadbpa</padig:set>
        <padig:set string="Admission and Discharge Books (PA), 1872-1900">psa_aadbpa00</padig:set>
        <padig:set string="Alphabetical (Old) Index to Continental Ledgers Nos. 1 and 2 (PA), 1775-1785">psa_aoiclnpa</padig:set>
        <padig:set string="Alphabetical Index to Naturalization Records, 1789-1880">psa_ainr1789</padig:set>
        <padig:set string="Alphabetical List of Accounts (PA)">psa_aloapp</padig:set>
        <padig:set string="Alphabetical List of Crews, 1798-1880">psa_alc1798</padig:set>
        <padig:set string="Alphabetical List of Names on Pennsylvania Monuments, undated">psa_alnpmu</padig:set>
        <padig:set string="Anatomical Board (PA) Cadaver Receiving Books, 1901-1965">psa_abcrb</padig:set>
        <padig:set string="Annual Reports of Passenger and Street Railway Companies (PA), 1861-1903">psa_arpsrcpa</padig:set>
        <padig:set string="Annual, Biennial, and Miscellaneous Reports of the Commission, 1945-2005">psa_abmrc1945</padig:set>
        <padig:set string="Applicant Files of the Pennsylvania Soldiers and Sailors Home, 1886-1949">psa_afpssh1949</padig:set>
        <padig:set string="Applications and Licenses Issued to Chiropodists (PA) Record, 1956-1974">psa_palicr</padig:set>
        <padig:set string="Applications for PA Teaching Certificates, 1866-1922">psa_afpatc</padig:set>
        <padig:set string="Arrivals and Clearances of Vessels, 1783-1880">psa_acv1783</padig:set>
        <padig:set string="Attorney General's Opinions (PA), 1892-1893, 1896-1898">psa_agopa1892</padig:set>
        <padig:set string="Bertillon Registration Books (PA), 1888-1895">psa_brbpa1895</padig:set>
        <padig:set string="Bloomsburg University (PA), Board of Trustees Minutes, 1927-1967">psa_bupabotm</padig:set>
        <padig:set string="Bloomsburg University (PA), Catalogs, 1867-1980">psa_bupac80</padig:set>
        <padig:set string="Bloomsburg University (PA), Faculty Government Minutes, 1970-1985">psa_bufgm</padig:set>
        <padig:set string="Bloomsburg University (PA), Student Government Council Minutes, 1949-1982">psa_bupasgcm</padig:set>
        <padig:set string="Bloomsburg University (PA), Yearbooks, 1915-1987">psa_bupay87</padig:set>
        <padig:set string="Board of Appraisers Minutes on Southern Border Property Damage (PA), 1863-1864">psa_bamsbpdpa1863</padig:set>
        <padig:set string="Board of Commissioners Journal to Erect the Western State Penitentiary, 1818-1835">psa_bcjewsppa</padig:set>
        <padig:set string="Board of Fish Commission (PA) Minutes, 1924-1969">psa_bfcm</padig:set>
        <padig:set string="Bond Records (PA), 1867-1921">psa_brpa</padig:set>
        <padig:set string="Bonds, Assignments, Contracts, Acts, Titles and Misc. Documents (PA), 1775-1949">psa_bacatmd</padig:set>
        <padig:set string="Boundary Survey Accounts (PA), 1782-1810">psa_bsapa</padig:set>
        <padig:set string="Braddock Road Accounts, 1755-1756">psa_bra1756</padig:set>
        <padig:set string="California University of PA, Board of Trustees Minutes, 1910-1992">psa_cuopabtm</padig:set>
        <padig:set string="California University of PA, Catalogs, 1869-1987">psa_cupac87</padig:set>
        <padig:set string="California University of PA, College Senior Theses, 1898-1903">psa_cupacst</padig:set>
        <padig:set string="California University of PA, Yearbooks, 1913-1917, 1919-1920, 1929-1986">psa_cupayyr</padig:set>
        <padig:set string="Candidates Examined for Appointments as Surgeons and Asst. Surgeons (PA), 1861-1865">psa_ceasas</padig:set>
        <padig:set string="Capitol Complex Restoration and Conservation Reports, 1897-2016">psa_ccrcr1897</padig:set>
        <padig:set string="Chambersburg War Damage Claim Applications (PA), 1866-1868">psa_cwdcapa1866</padig:set>
        <padig:set string="Chambersburg War Damage Claim Warrant Stub Books (PA), 1866">psa_cwdcwsbpa</padig:set>
        <padig:set string="Charter Books (PA), 1812-1875">psa_cbp</padig:set>
        <padig:set string="Cheyney University (PA), Catalogs, 1975-1987">psa_chupac87</padig:set>
        <padig:set string="Cheyney University (PA), Student Newspaper - The Record, 1979-1988">psa_chupasntr</padig:set>
        <padig:set string="Cheyney University (PA), Yearboooks, 1939-1988">psa_chupay98</padig:set>
        <padig:set string="Chronological List of Masters and Crews, 1798-1880">psa_clmc1798</padig:set>
        <padig:set string="City, Borough or Township Superintendents (PA) Record Book, 1866-1908">psa_pcbtsrb</padig:set>
        <padig:set string="Civil War Muster Rolls and Related Records, 1861-1866">psa_cwmrrr</padig:set>
        <padig:set string="Civil War Service and Pension Accounts (PA), 1861-1873">psa_cwsapapa</padig:set>
        <padig:set string="Clarion University (PA), Board of Trustees Minutes, 1886-1992">psa_clubtm</padig:set>
        <padig:set string="Clarion University (PA), Catalogs, 1891-1989">psa_cluc</padig:set>
        <padig:set string="Clarion University (PA), Faculty Forum Minutes, 1976-1988">psa_cluffm</padig:set>
        <padig:set string="Clarion University (PA), Faculty Senate Minutes, 1961-1988">psa_clufsm</padig:set>
        <padig:set string="Clarion University (PA), Graduate Catalogs, 1969-1989">psa_clugc</padig:set>
        <padig:set string="Clarion University (PA), Student Senate Minutes, 1942-1988">psa_clussm</padig:set>
        <padig:set string="Clarion University (PA), Student Yearbook: College Pathfinder, 1975-1987">psa_clusycp</padig:set>
        <padig:set string="Clarion University (PA), Summer Catalogs, 1958-1978">psa_clusc</padig:set>
        <padig:set string="Clarion University (PA), Yearbooks, 1909-1987">psa_cluy</padig:set>
        <padig:set string="Clothing and State Store Journal (PA), 1776-1777">psa_cassjpa77</padig:set>
        <padig:set string="Commissary Accounts (PA), 1775-1792">psa_capa</padig:set>
        <padig:set string="Commission Books (PA), 1775-1842">psa_cbpa</padig:set>
        <padig:set string="Commission Books, Miscellaneous (PA), 1912-1937">psa_cbmpa</padig:set>
        <padig:set string="Commission of Soldiers' Orphan Schools (PA) Annual Reports, 1870-1918">psa_csosar</padig:set>
        <padig:set string="Commission of Soldiers' Orphan Schools (PA) List of Deceased Students, 1865-1907">psa_csosld</padig:set>
        <padig:set string="Commission of Soldiers' Orphan Schools (PA) Orphans Leaving School, 1883-1903">psa_csosol</padig:set>
        <padig:set string="Commission Register for Mothers' Fund and Old Age Assistance Boards (PA), 1913-1937">psa_crmfoaab</padig:set>
        <padig:set string="Commissioners of Indian Trade Accounts, 1758-1766">psa_cita1766</padig:set>
        <padig:set string="Commissioners of Purchases Accounts (PA), 1780-1783">psa_cpapa</padig:set>
        <padig:set string="Commitment Papers (PA), 1841, 1861-1904">psa_cppa04</padig:set>
        <padig:set string="Communist Party (PA) Nomination Petitions for Philadelphia County, 1940, 1946">psa_cpnppc</padig:set>
        <padig:set string="Communist Party (PA) Nomination Petitions, 1938, 1940">psa_cppanp</padig:set>
        <padig:set string="Commutation and Parole Books (PA), 1907-1932">psa_capbpa</padig:set>
        <padig:set string="Commutation Books (PA), 1865-1918">psa_cbpa18</padig:set>
        <padig:set string="Commutation Books (PA), 1917-1958">psa_cbpa1958</padig:set>
        <padig:set string="Conduct Ledgers, 1889-1898, 1903-1905, 1916-1918">psa_cl1889</padig:set>
        <padig:set string="Conscientious Objector Depositions, 1862">psa_cod1862</padig:set>
        <padig:set string="Constitutional Convention of 1776 (PA) Minute Book">psa_cc1776mb</padig:set>
        <padig:set string="Constitutional Convention of 1837-1838 (PA) Accounts">psa_cc1837a</padig:set>
        <padig:set string="Constitutional Convention of 1837-1838 (PA) Committee Minute Books">psa_cc1837cmb</padig:set>
        <padig:set string="Constitutional Convention of 1837-1838 (PA) Journal">psa_cc1837j</padig:set>
        <padig:set string="Constitutional Convention of 1873 (PA) Journal">psa_cc1873j</padig:set>
        <padig:set string="Continental and State Money Account Book (PA), 1783-1784">psa_csmabpa</padig:set>
        <padig:set string="Continental Day and Waste Book (PA), 1775-1783">psa_cdwbpa</padig:set>
        <padig:set string="Continental Journals (PA), 1775-1785">psa_cjpa</padig:set>
        <padig:set string="Continental Ledgers (PA), 1775-1785">psa_clpa</padig:set>
        <padig:set string="Contract Book (PA), 1837-1856">psa_cbpa1837-56</padig:set>
        <padig:set string="Convict Affidavit Books (PA), 1835-1856">psa_cabpa70</padig:set>
        <padig:set string="Convict Description and Receiving Dockets (PA), 1872-1957">psa_cdardpa57</padig:set>
        <padig:set string="Convict Docket (PA), 1826-1859">psa_cdpa1826-59</padig:set>
        <padig:set string="Correspondence and Contracts (PA), 1886-1903">psa_cacpa03</padig:set>
        <padig:set string="Council of Censors (PA) Journals, 1783-1784">psa_ccj</padig:set>
        <padig:set string="Council of National Defense and Comm of Public Safety (PA) Scrapbooks, 1917-1920">psa_cndcpss</padig:set>
        <padig:set string="County and State (PA) Appointments, 1836-1940">psa_casa</padig:set>
        <padig:set string="County Officers' Accounts (PA), 1782-1809">psa_coapa</padig:set>
        <padig:set string="County Officers' Accounts (PA), 1809-1907">psa_coapa1809-1907</padig:set>
        <padig:set string="County Records Alphabetical Inventory, 1984">psa_crai1984</padig:set>
        <padig:set string="County Records Inventory by Office, 1984">psa_crio1984</padig:set>
        <padig:set string="County School Superintendents (PA) Record Book, 1854-1918">psa_pcssrb</padig:set>
        <padig:set string="County Tax Accounts (PA), 1781-1808">psa_ctapa08</padig:set>
        <padig:set string="Court of Admiralty Accounts (PA), 1779-1786">psa_coaapa</padig:set>
        <padig:set string="Crown Correspondence, 1726-1775">psa_cc1775</padig:set>
        <padig:set string="Daily Population Statistical Reports (PA), 1924, 1928-1929, 1940, 1960">psa_dpsrpa60</padig:set>
        <padig:set string="Danville State Hospital (PA) County Registers, 1872-1923">psa_dshcr</padig:set>
        <padig:set string="Danville State Hospital (PA) Court Commitment Books, 1884-1924">psa_dshccb</padig:set>
        <padig:set string="Danville State Hospital (PA) Male Case Index Books, 1880-1920">psa_dshmcib</padig:set>
        <padig:set string="Danville State Hospital (PA) Patient Ledgers, 1872-1921">psa_dshpl</padig:set>
        <padig:set string="Day Book of General Benedict Arnold (PA), 1777-1779">psa_dbgbapa</padig:set>
        <padig:set string="Day Books (PA), 1809-1879">psa_dbpa1809-1879</padig:set>
        <padig:set string="Death Warrants File (PA), 1874-1899">psa_dwfpa</padig:set>
        <padig:set string="Delaware River Fortification Accounts (PA), 1775-1798">psa_drfapa</padig:set>
        <padig:set string="Dental Licenses (PA) Record, 1897-1965">psa_pdlr</padig:set>
        <padig:set string="Department of Justice (PA) Board of Pardons Books, 1874-1934">psa_djbpb</padig:set>
        <padig:set string="Depreciation Certificate Accounts (PA), 1781-1792">psa_dcapa92</padig:set>
        <padig:set string="Descriptive Books (PA), 1826-1873">psa_dbpa1826-73</padig:set>
        <padig:set string="Descriptive Books of Regiments and Companies, 1861-1865">psa_dbrc1865</padig:set>
        <padig:set string="Descriptive Registers (PA), 1826-1876">psa_drpa1826-76</padig:set>
        <padig:set string="Descriptive Registers (PA), 1829-1903">psa_drpa1903</padig:set>
        <padig:set string="Discharge Books (PA), 1830-1858">psa_dbpa58</padig:set>
        <padig:set string="Discharge Descriptive Dockets (PA), 1873-1934">psa_dddpa</padig:set>
        <padig:set string="Dixmont State Hospital (PA) Annual Reports, 1848, 1850-1875">psa_dxshar</padig:set>
        <padig:set string="Dixmont State Hospital (PA) Female Patients' Clothing &amp; Property Books, 1890-1908">psa_dxshfpcpb</padig:set>
        <padig:set string="Dixmont State Hospital (PA) Indigent Patient Cards, 1893-1916">psa_dxshipc</padig:set>
        <padig:set string="Dixmont State Hospital (PA) Male Patients' Clothing &amp; Property Books, 1895-1908">psa_dxshmpcpb</padig:set>
        <padig:set string="East Stroudsburg University (PA), Catalogs, 1921-1922, 1931-1932, 1939-1987">psa_esuc</padig:set>
        <padig:set string="East Stroudsburg University (PA), Yearbooks, 1915-1982">psa_esuy</padig:set>
        <padig:set string="Edinboro University (PA), Catalogs, 1870-1871, 1896-1898, 1923-1987">psa_euc</padig:set>
        <padig:set string="Edinboro University (PA), Yearbooks, 1910-1972">psa_euy</padig:set>
        <padig:set string="Election Result for Presidential Primary and Constitutional Amendments (PA), 1968">psa_erppca</padig:set>
        <padig:set string="Ephrata Cloister File (PA), 1814-1956">psa_ecfpa</padig:set>
        <padig:set string="Exam Scores for (PA) Drugless Therapists, Chiropodists and Physiotherapists">psa_ecdtcp</padig:set>
        <padig:set string="Exam Scores for (PA) Medical Doctors, 1894-1927">psa_esmd</padig:set>
        <padig:set string="Exam Scores for (PA) Registered Pharmacists, 1963-1978">psa_esrp</padig:set>
        <padig:set string="Examination Reports for Candidates for Appointment as Medical Officers (PA), 1861-1865">psa_ercamo</padig:set>
        <padig:set string="Executive Correspondence, 1682-1775">psa_ec1775</padig:set>
        <padig:set string="Extradition Requisition Books (PA), 1865-1867, 1874-1891, 1900-1958">psa_erbpa</padig:set>
        <padig:set string="Extradition Warrant Books (PA), 1867-1964">psa_ewbpa</padig:set>
        <padig:set string="Farm Census Returns (PA), 1924, 1927">psa_fsr</padig:set>
        <padig:set string="Forfeited Estate Accounts (PA), 1777-1809">psa_feapa92</padig:set>
        <padig:set string="Funded and Unfunded Debt Accounts (PA), 1790-1809">psa_fudapa</padig:set>
        <padig:set string="General Assembly Committee Book, 1785">psa_gacb1785</padig:set>
        <padig:set string="General Assembly Minute Books, 1779-1781, 1783-1784, 1788">psa_gamb1779</padig:set>
        <padig:set string="General Assembly Petitions and Miscellaneous Records, 1776-1790">psa_gapmr</padig:set>
        <padig:set string="General Correspondence (PA), 1776-1809">psa_gcpa</padig:set>
        <padig:set string="General Correspondence (PA), 1891-1946, not inclusive">psa_gcpa1922</padig:set>
        <padig:set string="General Correspondence, 1700-1772">psa_gc1772</padig:set>
        <padig:set string="Geological Survey Accounts (PA), 1837-1840, 1851-1857, 1875">psa_gsapa1837</padig:set>
        <padig:set string="Governor John F. Hartranft (PA) Correspondence and Issue Files, 1873-1879">psa_gjfhcif</padig:set>
        <padig:set string="Governor's Accounts including Lists of Marriage, Tavern, Peddlers Licenses and Ships' Registers, 1742-1752, 1759-1763">psa_gailmtplsr</padig:set>
        <padig:set string="Governor's Minutes (PA), 1838-1959">psa_gmpa1845</padig:set>
        <padig:set string="Governor's Proclamations (PA), 1930-1956">psa_gppa1930</padig:set>
        <padig:set string="Harrisburg State Hospital (PA), Account of Clothing Issued to Female Patients, 1851-1862">psa_hshacifp</padig:set>
        <padig:set string="Harrisburg State Hospital (PA), Journal of John Curwen, 1851-1871">psa_hshjjc</padig:set>
        <padig:set string="Harrisburg State Hospital (PA), Patient Register, 1930-1932">psa_hshpr</padig:set>
        <padig:set string="Harrisburg Unit Unpublished Manuscripts, Guide to the Manuscript Collections of the Archives Division, 1942, undated">psa_huum1942</padig:set>
        <padig:set string="Indents Delivered to the Treasurer (PA), 1793">psa_idthtpa</padig:set>
        <padig:set string="Index (PA) of Licensed Practitioners of Medicine, 1894-1981">psa_ilpmp</padig:set>
        <padig:set string="Index of Prisoners (PA), circa mid-1930s - early 1950s">psa_ioppacm1950</padig:set>
        <padig:set string="Index to Ledger AA, 1777-1788">psa_ilaa1977</padig:set>
        <padig:set string="Index to Philadelphia Register of Deaths, 1803-1860">psa_iprd1803</padig:set>
        <padig:set string="Indian Commissioners' Accounts (PA), 1784-1785">psa_icapa85</padig:set>
        <padig:set string="Indian Commissioners' Accounts (PA), 1784-1792">psa_icapa92</padig:set>
        <padig:set string="Indian Trader Licenses, 1765-1771">psa_itl1771</padig:set>
        <padig:set string="Indiana University (PA), Scrapbooks, 1940-1976">psa_iups1940</padig:set>
        <padig:set string="Industrial and Railroad Police Registers (PA), 1889-1912, 1927-1931">psa_irprpa</padig:set>
        <padig:set string="Inmate Transfer Register (Discharge Ledger) (PA), 1954-1957">psa_itrdlpa</padig:set>
        <padig:set string="Internal Improvements File (PA), 1777-1809">psa_iifpa09</padig:set>
        <padig:set string="Inventory of Canal Commissioners' Maps in the Pennsylvania State Archives, 1968">psa_iccmpsa1968</padig:set>
        <padig:set string="Investigation Reports of the State Boards of Charities (PA), 1890-1935">psa_risbctpa</padig:set>
        <padig:set string="Journals (PA), 1799-1808">psa_jpa</padig:set>
        <padig:set string="Journals A-AAA (PA), 1775-1790">psa_jaaaa</padig:set>
        <padig:set string="Journals of the General Superintendent (PA), 1891-1922">psa_jotgspa22</padig:set>
        <padig:set string="Justice of the Peace (PA) Commission Registers, 1878-1910">psa_jopcr1878</padig:set>
        <padig:set string="Korean War Compensation Application Batch Sheets and Serial Number Indexes, 1955-1967">psa_kwcabssni</padig:set>
        <padig:set string="Ku Klux Klan (PA) General Accounts, 1925-1940">psa_kkkga</padig:set>
        <padig:set string="Ku Klux Klan (PA) General Correspondence, 1922-1929, 1932, 1934-1940">psa_kkkgc</padig:set>
        <padig:set string="Ku Klux Klan (PA) General Files, 1923-1940">psa_kkkgf</padig:set>
        <padig:set string="Ku Klux Klan (PA) Kleagle Robe Reports, 1924-1925">psa_kkkkrr</padig:set>
        <padig:set string="Kutztown University (PA), Board of Trustees Minutes, 1866-1986">psa_kubtm</padig:set>
        <padig:set string="Kutztown University (PA), Catalogs, 1866-1988">psa_kuc</padig:set>
        <padig:set string="Kutztown University (PA), Faculty Senate Minutes, 1964-1987">psa_kufsm</padig:set>
        <padig:set string="Kutztown University (PA), Student Government Board Minutes, 1977-1987">psa_kusgbm</padig:set>
        <padig:set string="Kutztown University (PA), Student Handbook- The Key, 1936-1989">psa_kush</padig:set>
        <padig:set string="Kutztown University (PA), Yearbooks, 1911-1986">psa_kuy</padig:set>
        <padig:set string="Ledgers A-AA (PA), 1775-1788">psa_laaapa88</padig:set>
        <padig:set string="Letter Book (PA), 1837-1859">psa_lbpa1837-59</padig:set>
        <padig:set string="Letter Book, Accounts, and Related Records of the Auditors of Accounts (PA) 1777-1784">psa_lbarraapa</padig:set>
        <padig:set string="Letter Press Books (PA), 1879-1880, 1884-1895">psa_lpppa1879</padig:set>
        <padig:set string="Letters Patent (PA), 1814-1874, 1902-1927">psa_lpp</padig:set>
        <padig:set string="Letters To and From Prisoners (PA), 1845">psa_ltafppa</padig:set>
        <padig:set string="Licenses (PA) Issued on Licenses from Other States, 1963-1972">psa_lilos</padig:set>
        <padig:set string="Licenses Issued to Chiropodists (PA) Record, 1914-1956">psa_plicr</padig:set>
        <padig:set string="Lincoln University (PA), Publications, 1884-1991">psa_lupap</padig:set>
        <padig:set string="List of Printed Accounts (PA) in the Comptroller General's Office, 1777-1789">psa_lpacgo</padig:set>
        <padig:set string="List of Those Receiving State Money For Whom No Account Was Raised (PA), c.1790">psa_ltrsmpa</padig:set>
        <padig:set string="Listing of (PA) Licensed Drugless Therapists, 1914-1951">psa_lldt</padig:set>
        <padig:set string="Lists of Deserters and Substitute Deserters, 1861-1866">psa_ldsd1866</padig:set>
        <padig:set string="Lists of Sick and Wounded Soldiers, Pennsylvania Volunteers, 1861-1864">psa_lswspv1864</padig:set>
        <padig:set string="Lock Haven University (PA), Board of Trustees Minutes, 1914-1984">psa_lhubotm</padig:set>
        <padig:set string="Lock Haven University (PA), Bulletins and Catalogs, 1878-1897, 1911-1970">psa_lhubac</padig:set>
        <padig:set string="Lock Haven University (PA), Yearbooks, 1913-1985">psa_lhuy1985</padig:set>
        <padig:set string="Mansfield University (PA), Catalogs, 1864-1987">psa_muc1987</padig:set>
        <padig:set string="Mansfield University (PA), Faculty Minutes for Assemblies, Councils, and Senates, 1965-1987">psa_mufm1987</padig:set>
        <padig:set string="Mansfield University (PA), Treasurer's Minutes, 1855-1959">psa_mutm1959</padig:set>
        <padig:set string="Mansfield University (PA), Yearbooks, 1918-1986">psa_mupay</padig:set>
        <padig:set string="Manual for Newspaper Transcription, 1941">psa_mnt1941</padig:set>
        <padig:set string="Medical Examination Papers (PA), 1861-1865">psa_meppa</padig:set>
        <padig:set string="Medical Licenses (PA) Issued on Licenses from Other States Record, 1894-1963">psa_pmlilosr</padig:set>
        <padig:set string="Medical Licenses (PA) Recommended By the State Medical Society Record, 1894-1911">psa_pmlrsmsr</padig:set>
        <padig:set string="Medical Licenses (PA) Record, 1912-1964">psa_pmlr</padig:set>
        <padig:set string="Medical Statistics Books (PA), 1883-1900">psa_msbpa00</padig:set>
        <padig:set string="Meeting Minutes and Related Records (PA), 1972-1976">psa_mmarrpa76</padig:set>
        <padig:set string="Memoranda Book (PA), 1791">psa_mbpa91</padig:set>
        <padig:set string="Memoranda Book of Old Accounts (PA), undated">psa_mbooapa</padig:set>
        <padig:set string="Memoranda of Account Book (PA), 1791">psa_mabpa1791</padig:set>
        <padig:set string="Mexican War Accounts and Related Papers (PA), 1846-1880">psa_mwarp</padig:set>
        <padig:set string="Mexican War Service Index (PA), 1846-1848">psa_mwsipa</padig:set>
        <padig:set string="Military Claims File: Claims not Settled (PA), 1862-1905">psa_mcfcnspa</padig:set>
        <padig:set string="Military Claims File: Claims Settled, 1862-1905">psa_mcfcs1905</padig:set>
        <padig:set string="Military Pension Accounts and Related Papers (PA), circa 1789-1883">psa_mpaarppac</padig:set>
        <padig:set string="Militia Absentee Return Record for Philadelphia City, 1777-1791">psa_marrpc</padig:set>
        <padig:set string="Militia Certificates Received from the Receiver General (PA), 1789-1793">psa_mcrfrg</padig:set>
        <padig:set string="Militia Exemption Books (PA), 1801-1813">psa_mebpa1813</padig:set>
        <padig:set string="Militia Fine Exoneration Records (PA), 1777-1793">psa_mferpa</padig:set>
        <padig:set string="Militia Loan Accounts, 1781-1792">psa_mla1781</padig:set>
        <padig:set string="Minority Business Development Authority (PA) Minutes, 1979-1993">psa_mbdam</padig:set>
        <padig:set string="Minute Books (PA), 1893-1977">psa_mbpa1893</padig:set>
        <padig:set string="Minute Books of the Board of Inspectors and Board of Trustees (PA), 1826-1931">psa_mbbibt31</padig:set>
        <padig:set string="Minute Books of the Board of Inspectors and Board of Trustees (PA), 1829-1889">psa_mbbibt</padig:set>
        <padig:set string="Minutes (The Provincial Record), 1682-1775">psa_mtpr1775</padig:set>
        <padig:set string="Minutes of the Board of Appraisers of Chambersburg War Damages (PA), 1866">psa_mbacwd1866</padig:set>
        <padig:set string="Minutes of the Board of Inspectors-Trustees Acting as a Parole Board, 1910-1930">psa_mbitapbpa</padig:set>
        <padig:set string="Minutes of the Board of Trustees (PA), 1931-1954">psa_motbotpa</padig:set>
        <padig:set string="Minutes of the Pennsylvania Historical Commission, 1924-1925, 1927-1945">psa_mphc1924</padig:set>
        <padig:set string="Minutes, Correspondence and Related Materials of the State Veterans Commission, 1962-1963, 1972-2005">psa_mcrmsvc</padig:set>
        <padig:set string="Miscellaneous Accounts Including Records of Transactions Involving the Commonwealth and the United States, 1782-1809">psa_mairtic</padig:set>
        <padig:set string="Miscellaneous Descriptive Books (PA), 1829-1842">psa_mdbpa1829</padig:set>
        <padig:set string="Miscellaneous Discharge Certificates, 1861-1866">psa_mdc1866</padig:set>
        <padig:set string="Miscellaneous Financial Documents (PA) 1845-1955, not inclusive, undated">psa_mfdpa1955</padig:set>
        <padig:set string="Miscellaneous Ledgers (PA), 1763-1883">psa_mlpa1763</padig:set>
        <padig:set string="Miscellaneous Papers, 1664-1775">psa_mp1775</padig:set>
        <padig:set string="Mortgage Books (PA), 1774-1788">psa_mbpa</padig:set>
        <padig:set string="Mortgages and Related Valuations (PA), 1773-1793">psa_mrvpa</padig:set>
        <padig:set string="Mothers Pension Account Books (PA), 1913-1917">psa_mpabpa17</padig:set>
        <padig:set string="Naturalization Lists of the Supreme Court and Courts of Nisi Prius, 1740-1773">psa_nlsccnp</padig:set>
        <padig:set string="New Loan Accounts, 1776-1795">psa_nla1776</padig:set>
        <padig:set string="Notary Public (PA) Commission Registers, 1893-1945">psa_nppacr</padig:set>
        <padig:set string="Notary Public (PA) Termination Card Index, 1945-1964">psa_mppatci</padig:set>
        <padig:set string="Office of Lieutenant Governor (PA) Board of Pardons Minutes, 1974-1999">psa_olgbpm</padig:set>
        <padig:set string="Officers Claim Book for Arrears in Clothing (PA), 1778-1791">psa_ocbfaic</padig:set>
        <padig:set string="Officers Clothing Account Book (PA), 1791">psa_ocabpa</padig:set>
        <padig:set string="Old Economy Register of the Members of the Harmony Society, 1805-1905">psa_oermhs</padig:set>
        <padig:set string="Opinions of the Attorney General (PA), 1874-1927">psa_ootagpa</padig:set>
        <padig:set string="Optometrical Licenses (PA), 1918-1970">psa_ol</padig:set>
        <padig:set string="PA Soldiers' and Sailors' Home in Erie (PA) Admission and Medical Book, 1893-1922">psa_passam</padig:set>
        <padig:set string="PA Soldiers' and Sailors' Home in Erie (PA) Death Record Book, 1886-1925">psa_passdr</padig:set>
        <padig:set string="PA Soldiers' and Sailors' Home in Erie (PA) Discharge and Offense Book, 1895-1909">psa_passdo</padig:set>
        <padig:set string="PA Soldiers' and Sailors' Home in Erie (PA) General Record of Members, 1888-1907">psa_passgr</padig:set>
        <padig:set string="PA Soldiers' and Sailors' Home in Erie (PA) Hospital Record Book, 1889-1901">psa_passhr</padig:set>
        <padig:set string="PA Soldiers' and Sailors' Home in Erie (PA) Hospital Records, 1890-1900">psa_passhr2</padig:set>
        <padig:set string="PA Soldiers' and Sailors' Home in Erie (PA) Patient Histories, 1903-1925">psa_passph</padig:set>
        <padig:set string="PA Soldiers' and Sailors' Home in Erie (PA) Patient Record Books, 1886-1949">psa_passpr</padig:set>
        <padig:set string="Parole and Respite Books (PA), 1910-1942">psa_parbpa</padig:set>
        <padig:set string="Parole Prisoners' Date of Discharge Books (PA), circa 1910-1957">psa_ppdodbpac</padig:set>
        <padig:set string="Paroled Prisoner Statistical Book (PA), 1910-1931">psa_psbpa1931</padig:set>
        <padig:set string="Pennsylvania Notes, 1937-1939">psa_pn1937</padig:set>
        <padig:set string="Permanent Teaching Certificates (PA) Record Books, 1868-1908">psa_pptcrb</padig:set>
        <padig:set string="Philadelphia City General Muster Roll Books (PA), 1777-1784">psa_pcgmrb</padig:set>
        <padig:set string="Philadelphia City Lieutenants Office General Return Book (PA), 1777-1782">psa_pclogrb</padig:set>
        <padig:set string="Physicians (PA) Register, 1870-1917">psa_ppr</padig:set>
        <padig:set string="Physicians' Record of Prisoners, 1889-1910">psa_prp1889</padig:set>
        <padig:set string="Polk Center (PA) Glass Plate Negatives">psa_pcgpn</padig:set>
        <padig:set string="Population Indexes (PA), circa 1826-1960">psa_pipac60</padig:set>
        <padig:set string="Population Indexes (PA), circa 1900">psa_pipa1900</padig:set>
        <padig:set string="Population Record Books of the Pennsylvania Soldiers and Sailors Home, 1864-1883">psa_prbpssh</padig:set>
        <padig:set string="Port of Philadelphia Records: Abstracts of Duties and Drawbacks, 1784-1789">psa_popradd1784</padig:set>
        <padig:set string="Port of Philadelphia Records: Account of Duties and Drawbacks, 1783">psa_popradd1783</padig:set>
        <padig:set string="Port of Philadelphia Records: Accounts and Certificates of the Collector of Head Money, 1791-1808">psa_popracchm</padig:set>
        <padig:set string="Port of Philadelphia Records: Accounts and Receipts of the Tonnage Office, 1783-1789">psa_poprarto</padig:set>
        <padig:set string="Port of Philadelphia Records: Accounts Current of the Collector's Office, 1784-1789">psa_popracco</padig:set>
        <padig:set string="Port of Philadelphia Records: Bonds and Papers Relating to Duties on Negro and Mulatto Slaves, 1720-1788">psa_poprbprdnms</padig:set>
        <padig:set string="Port of Philadelphia Records: Cargo Manifests, Inventories, and Bills of Lading, 1773-1833">psa_poprcmibl</padig:set>
        <padig:set string="Port of Philadelphia Records: Coasting Permits, 1796, 1806">psa_poprcp1796</padig:set>
        <padig:set string="Port of Philadelphia Records: Drawbacks and Vouchers Paid by the Collector of Duties, 1784-1789">psa_poprdvpcd</padig:set>
        <padig:set string="Port of Philadelphia Records: Expenditures and Receipts of the Collector's Office, 1784-1789">psa_poprerco</padig:set>
        <padig:set string="Port of Philadelphia Records: Lists of Bonds Cancelled, 1774-1775">psa_poprlobc</padig:set>
        <padig:set string="Port of Philadelphia Records: Lists of Bonds, 1774-1775">psa_poprlob</padig:set>
        <padig:set string="Port of Philadelphia Records: Miscellaneous Records, 1782-1834">psa_poprmr</padig:set>
        <padig:set string="Port of Philadelphia Records: Record Books of Bonds Due the Custom House, 1785-1788">psa_poprrbbdch</padig:set>
        <padig:set string="Port of Philadelphia Records: Records of the Health Office, 1783-1798">psa_poprroho</padig:set>
        <padig:set string="Port of Philadelphia Records: Records of the Wardens of the Port, 1776-1809">psa_poprrwp</padig:set>
        <padig:set string="Port of Philadelphia Records: Register of Drawbacks on Goods Exported, 1785-1786">psa_poprrdge</padig:set>
        <padig:set string="Port of Philadelphia Records: Registers of Duties Paid on Imported Goods, 1781-1787">psa_poprrdpig</padig:set>
        <padig:set string="Port of Philadelphia Records: Registers of Tonnage Duties, 1775-1776, 1784-1789">psa_poprrtd</padig:set>
        <padig:set string="Port of Philadelphia Records: Registry Statements of Cargo Contents Duties Paid and Drawbacks, 1782-1785, 1788">psa_poprrsccdpd</padig:set>
        <padig:set string="Port of Philadelphia Records: Reports of Imposts Due, 1783-1788">psa_poprroid</padig:set>
        <padig:set string="Port of Philadelphia Records: Vessel Registry Vouchers, 1781-1782">psa_poprvrv</padig:set>
        <padig:set string="Port Physician's Certificates, 1741, 1753-1755">psa_ppc1741</padig:set>
        <padig:set string="Postcards (PA)">psa_pc</padig:set>
        <padig:set string="Posters (PA)">psa_p</padig:set>
        <padig:set string="Prisoner Registers (PA), 1910-1970">psa_prpa1910-70</padig:set>
        <padig:set string="Prisoners Paroled and Discharged Book (PA), 1887-1918">psa_ppadbpa18</padig:set>
        <padig:set string="Prisoners' Record, 1889-1929">psa_pr1889</padig:set>
        <padig:set string="Provincial Officers' Sureties, 1742-1776">psa_pos1776</padig:set>
        <padig:set string="Publications (Including the Expedition of Baron de Longueuil), 1939-1942">psa_piebl1939</padig:set>
        <padig:set string="Reception Descriptive Book (PA), 1879-1884">psa_rdbpa1884</padig:set>
        <padig:set string="Record Book of Candidates by the State Medical Board (PA), 1862">psa_rbcsmb</padig:set>
        <padig:set string="Record Book of Claims for Arrears of Pay and Bounty (PA), 1864-1869">psa_rbcapb</padig:set>
        <padig:set string="Record Book of Medical Officers of the Pennsylvania Volunteers (PA), 1861-1864">psa_rbmopv</padig:set>
        <padig:set string="Record Books of Capital Cases (PA), 1894-1969">psa_rbocc</padig:set>
        <padig:set string="Record of (PA) Dental Licenses, 1965-1973">psa_rdl</padig:set>
        <padig:set string="Record of (PA) Medical Licenses, 1964-1971">psa_rml</padig:set>
        <padig:set string="Record of Applications and Licenses Issued to (PA) Chiropodists, 1974-1982">psa_ralic</padig:set>
        <padig:set string="Record of Chambersburg War Damage Claim Final Awards (PA), 1866">psa_rcwdcfapa1866</padig:set>
        <padig:set string="Record of County and Federal Prisoners (PA), 1857-1870">psa_rcfppa70</padig:set>
        <padig:set string="Record of Maximum Sentences, 1915-1918">psa_rms1815</padig:set>
        <padig:set string="Record of Men Paroled, 1890-1894, 1909-1913">psa_rmp1890</padig:set>
        <padig:set string="Record of Parole Violators (PA), 1942-1954">psa_ropvpa54</padig:set>
        <padig:set string="Record of Pennsylvania Volunteers (PA) in the Spanish-American War, 1898">psa_rpvsaw</padig:set>
        <padig:set string="Record of Special Punishments, 1889-1925, 1931">psa_rsp1889</padig:set>
        <padig:set string="Recorder of Deeds Accounts (PA), 1947-1964">psa_rdapa</padig:set>
        <padig:set string="Records of Drafted Men and Substitutes (PA), 1862">psa_rdmspa</padig:set>
        <padig:set string="Reformatory Record (Weekly Prison Publication), 1890-1936">psa_rrwpp</padig:set>
        <padig:set string="Register of Accounts Received from the Register General (PA), 1790-1792">psa_rarfrg</padig:set>
        <padig:set string="Register of Executive Accounts (PA), 1784-1791">psa_reapa</padig:set>
        <padig:set string="Register of Sick and Wounded Soldiers, circa 1861-1865">psa_rsws1865</padig:set>
        <padig:set string="Registers of Mine Accidents (PA) for the Anthracite Districts, 1899-1972">psa_rmaad</padig:set>
        <padig:set string="Registers of Mine Accidents (PA) for the Bituminous Districts, 1899-1972">psa_rmabd</padig:set>
        <padig:set string="Registers of Surgeons and Assistant Surgeons (PA), 1861-1866">psa_rsaspa</padig:set>
        <padig:set string="Registers of Visitors (PA), 1829-1854">psa_rovpa</padig:set>
        <padig:set string="Registrar's Book of Governor Keith's Court of Chancery, 1720-1736">psa_rbofkcoc</padig:set>
        <padig:set string="Registration Figures (PA), 1950, 1960, 1964, 1966-1972">psa_rfpa1950</padig:set>
        <padig:set string="Registration Record of Practitioners of Medicine and Surgery (PA), 1881-1889">psa_rrpmspa1881</padig:set>
        <padig:set string="Report Book of the State Treasurer (PA), 1783">psa_rbstpa</padig:set>
        <padig:set string="Reports of Committee of the Assembly on State of Public Accounts (PA), 1778-1780">psa_rcaspa</padig:set>
        <padig:set string="Return Book of Officers and Soldiers to Whom Patents Were Not Issued, undated">psa_rboswpwni</padig:set>
        <padig:set string="Return Book of the Pennsylvania Line Entitled to Donation Lands, undated">psa_rbpledl</padig:set>
        <padig:set string="Revolutionary War Accounts and Miscellaneous Records (Associators Accounts), 1775-1777">psa_rwamraa</padig:set>
        <padig:set string="Revolutionary War Accounts and Miscellaneous Records (Line Accounts), 1775-1809">psa_rwamrla</padig:set>
        <padig:set string="Revolutionary War Military Abstract Card File, 1785-1893">psa_rwmacf</padig:set>
        <padig:set string="Revolutionary War Pension File (PA), 1809-1893">psa_rwpfpa1809</padig:set>
        <padig:set string="Revolutionary War Pension List Book (PA), 1834-1838">psa_rwplbpa38</padig:set>
        <padig:set string="Richard Partridge Account Book, 1740-1751">psa_rpab1740</padig:set>
        <padig:set string="Sanitary Water Board (PA) Minute Books, 1923-1931, 1969">psa_swbmb</padig:set>
        <padig:set string="School Attendance Record (PA), 1935-1936">psa_sarpa</padig:set>
        <padig:set string="School Examination Question Book (PA), 1892-1897">psa_seqbpa</padig:set>
        <padig:set string="School Offense and Punishment Book (PA), 1936">psa_sopbpa</padig:set>
        <padig:set string="Schuylkill Navigation Company, Schuylkill River Project Engineers' Records, 1850-1940">psa_sncsrper</padig:set>
        <padig:set string="Scrapbooks (PA), 1884-1893, 1908-1917, 1925-1926">psa_spa1926</padig:set>
        <padig:set string="Secretary of Agriculture (PA) Scrapbooks, 1918-1940">psa_sas</padig:set>
        <padig:set string="Secretary's Accounts, 1738-1774">psa_sa1738</padig:set>
        <padig:set string="Selective Sales and Use Tax Tentative Regulations from (PA) Revenue Department, 1956">psa_ssuttrpa</padig:set>
        <padig:set string="Senate Committee Books, 1810-1850, 1897-1899">psa_scb1810</padig:set>
        <padig:set string="Settlement Registers (PA) 1792-1794">psa_srpa94</padig:set>
        <padig:set string="Shippensburg University (PA), Board of Trustees Minutes, 1929-1971, 1979-1992">psa_shubotm</padig:set>
        <padig:set string="Slippery Rock University (PA), Academic Forum Agenda and Minutes, 1966-1987">psa_sruafam</padig:set>
        <padig:set string="Slippery Rock University (PA), Alumni News, 1945-1971">psa_sruan</padig:set>
        <padig:set string="Slippery Rock University (PA), Board of Trustees Minutes, 1968-1992">psa_srubotm</padig:set>
        <padig:set string="Slippery Rock University (PA), Catalogs and Bulletins, 1889-1988">psa_srucb</padig:set>
        <padig:set string="Slippery Rock University (PA), Student Literary Journal: Ginger Hill, 1956-1988">psa_srusljgh</padig:set>
        <padig:set string="Slippery Rock University (PA), Yearbooks, 1898-1987">psa_sruy1898</padig:set>
        <padig:set string="Specie Day Book and Waste Books (PA), 1775-1790">psa_sdbawb</padig:set>
        <padig:set string="Specie Journals (PA), 1775-1790">psa_sjpa90</padig:set>
        <padig:set string="Specie Ledger (PA), 1775-1790">psa_slpa90</padig:set>
        <padig:set string="Specie Ledger's Balance Books (PA), 1775-1790">psa_slbbpa</padig:set>
        <padig:set string="Sportsman Advisory Councils (PA) Files, 1996-2003">psa_sacf</padig:set>
        <padig:set string="State Board of Education (PA) Minute Books, 1911-1920, 1925-1982">psa_sbemb</padig:set>
        <padig:set string="State Board of Motion Picture Censors (PA) Examination Applications, 1915-1951">psa_sbmpcafe</padig:set>
        <padig:set string="State Board of Motion Picture Censors (PA) General Correspondence, 1924-1956">psa_sbmpcgc</padig:set>
        <padig:set string="State Board of Motion Picture Censors (PA) Legal Briefs, 1915-1921, 1928-1940">psa_sbmpclb</padig:set>
        <padig:set string="State Board of Motion Picture Censors (PA) Minutes, 1939-1956">psa_sbmpcm</padig:set>
        <padig:set string="State Board of Motion Picture Censors (PA) Reports, 1925-1951">psa_sbmpcr</padig:set>
        <padig:set string="State Board of Motion Picture Censors (PA) Rules, Procedures, Forms, 1915-1956">psa_sbmpcrpf</padig:set>
        <padig:set string="State Certificates (PA) for College Graduates Record Book, 1893-1911">psa_psccgrb</padig:set>
        <padig:set string="State Departmental Accounts, 1782-1809">psa_sda1782</padig:set>
        <padig:set string="State Forestry Commission (PA) Biennial Reports, 1901-1919">psa_psfcbr</padig:set>
        <padig:set string="State Forestry Commission (PA) General Correspondence and Letter Press Books">psa_psfcgfclpb</padig:set>
        <padig:set string="State Forestry Commission (PA) General Files, 1878, 1895">psa_psfcgf</padig:set>
        <padig:set string="State Forestry Commission (PA) Meeting Minutes, 1899-1923">psa_psfcmm</padig:set>
        <padig:set string="State Forestry Commission (PA) Publications, 1898-1924">psa_psfcp</padig:set>
        <padig:set string="State of Finances of the Commonwealth of PA by John Nicholson (PA), 1787">psa_sfcpa</padig:set>
        <padig:set string="State Police (PA) Descriptive Books of Troopers, 1906-1939">psa_pspdbt</padig:set>
        <padig:set string="State Police (PA) Strike Reports, 1936-1941">psa_pspsr</padig:set>
        <padig:set string="State Police (PA) Troop Reports, 1906-1930">psa_psptr</padig:set>
        <padig:set string="State Tax Equalization Board (PA) Minutes, 1947-1999">psa_stebm</padig:set>
        <padig:set string="State Treasurer's Reports (PA), 1790-1798, 1800-1809">psa_strpa1770</padig:set>
        <padig:set string="Statement of Public Accounts Book (PA), 1790-1791">psa_spabpa</padig:set>
        <padig:set string="Statistical Books (PA), 1835-1852, 1871-1909, 1911-1913, 1915">psa_sbpa1835</padig:set>
        <padig:set string="Substitutes' Depositions (PA), 1862">psa_sdpa</padig:set>
        <padig:set string="Supreme, Superior, Common Pleas, and Orphans Courts Judge (PA) Commission Registers, 1893-1942">psa_sscpacjcr</padig:set>
        <padig:set string="Surgeons' Reports (PA), 1861-1864">psa_srpa61</padig:set>
        <padig:set string="The Venango Trail, 1940">psa_tvt1940</padig:set>
        <padig:set string="Time Books (PA), 1889-1950">psa_tbpa1950</padig:set>
        <padig:set string="Time Ledger for Length of Sentences (PA), 1917-1967">psa_tlflospa</padig:set>
        <padig:set string="Transcripts and Translations (Including the Journal of Chaussegras de Lery), 1938-1942">psa_tatijcdl</padig:set>
        <padig:set string="Transcripts of Index of Vessels, 1874-1937, transcribed circa 1937-1941">psa_tiv1974</padig:set>
        <padig:set string="Transcripts of Port Warden's Minutes, 1766-1880">psa_tpwm1766</padig:set>
        <padig:set string="Transcripts of Records of Wrecks, 1874-1937, transcribed circa 1937-1941">psa_trw1874</padig:set>
        <padig:set string="Transcripts of Slave Manifests, 1800-1841, transcribed circa 1937-1941">psa_tsm1800</padig:set>
        <padig:set string="Tryal Balance Book (PA)">psa_tbbpa</padig:set>
        <padig:set string="Turnpike Commission (PA) Contract Files, 1938-1972">psa_tccf1938</padig:set>
        <padig:set string="Turnpike Commission (PA) Engineering, Cross-Section, Plan, Profile Drawings,1939-1964">psa_tcecppd</padig:set>
        <padig:set string="Turnpike Commission (PA) Engineering, Field Survey Notebooks, 1938-1971">psa_tcefsn</padig:set>
        <padig:set string="Unidentified Indexes (PA) Day Books, and New Loan Accounts, 1780-1809">psa_uidbnla</padig:set>
        <padig:set string="United States Lottery Stub Book (PA), 1776">psa_uslsbpa</padig:set>
        <padig:set string="Veterinary (PA) Registration Books, 1905-1961">psa_vrb</padig:set>
        <padig:set string="Visitors Register (PA), 1848-1860">psa_vrpa1860</padig:set>
        <padig:set string="Volunteer Police Registers (PA), 1941-1946">psa_vprpa</padig:set>
        <padig:set string="War of 1812 Militia Accounts (PA), 1812-1827">psa_w1812ma</padig:set>
        <padig:set string="War of 1812 Militia Accounts Final Settlement with United States (PA), 1812-1827">psa_w1812mafs</padig:set>
        <padig:set string="Warden's Daily Journals (PA), 1829-1961">psa_wdjpa</padig:set>
        <padig:set string="Warden's Daily Journals (PA), 1869-1875">psa_wdjpa1860</padig:set>
        <padig:set string="Warden's Daily Journals (PA), 1927-1956">psa_wdjpa1956</padig:set>
        <padig:set string="Warrant Books (PA), 1789-1794; Warrant Register, 1797-1802">psa_wbpa1794</padig:set>
        <padig:set string="Warrant Books (PA), 1791-1808">psa_wbpa08</padig:set>
        <padig:set string="Warrant Counterpart Records, 1792-1799, 1806-1808">psa_wcr1792</padig:set>
        <padig:set string="Warrant Registers and Index (PA), 1782-1807">psa_wraipa07</padig:set>
        <padig:set string="Warrants (PA), 1778-1809">psa_warrpa</padig:set>
        <padig:set string="Waste Book Indexes (PA), 1776-1792">psa_wbipa92</padig:set>
        <padig:set string="Waste Book of Thomas Murray, 1702-1707">psa_wbotm1702</padig:set>
        <padig:set string="Waste Books (PA), 1776-1792">psa_wbpa92</padig:set>
        <padig:set string="West Chester University (PA), Board of Trustees Minutes, 1869-1992">psa_wcubtm</padig:set>
        <padig:set string="West Chester University (PA), Catalogs, 1871-1989">psa_wcuc1871</padig:set>
        <padig:set string="West Chester University (PA), School Newspaper, 1924-1988">psa_wcusn</padig:set>
        <padig:set string="West Chester University (PA), Yearbooks, 1910-1987">psa_wcuy1910</padig:set>
        <padig:set string="Western Expedition (Whiskey Rebellion) Accounts, 1794-1804">psa_wewra</padig:set>
        <padig:set string="Woodville State Hospital (PA), Patient Register Books of Allegheny Co Hosp for Insane">psa_wdshprbachi</padig:set>
        <padig:set string="Works Progress Administration Bituminous Coal &amp; Coal Mining Maps (PA), 1934-1936">psa_wpabccmm</padig:set>
        <padig:set string="World War I Posters (PA)">psa_wwip</padig:set>
    </xsl:param>
</xsl:stylesheet>
