<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:dcterms="http://purl.org/dc/terms/"
    xmlns:dpla="http://dp.la/about/map/"
    xmlns:padig="http://padigital.org/ns"
    xmlns:edm="http://www.europeana.eu/schemas/edm/"
    xmlns:oclcdc="http://worldcat.org/xmlschemas/oclcdc-1.0/"
    xmlns:oclcterms="http://purl.org/oclc/terms/"
    xmlns:oai="http://www.openarchives.org/OAI/2.0/"
    xmlns:oai_dc='http://www.openarchives.org/OAI/2.0/oai_dc/'
    xmlns:oclc="http://purl.org/oclc/terms/"
    xmlns:oai_qdc="http://worldcat.org/xmlschemas/qdc-1.0/"
    xmlns:schema="http://schema.org"
    xmlns:svcs="http://rdfs.org/sioc/services" version="2.0">

    <!-- lookup table to identify LVDA collections -->
    <xsl:param name="powerSetInt">
        <padig:setInt string="Lackawanna Valley Digital Archives">papd_pscrl-cot</padig:setInt>
        <padig:setInt string="Lackawanna Valley Digital Archives">papd_pscrl-ccos</padig:setInt>
        <padig:setInt string="Lackawanna Valley Digital Archives">papd_pscrl-cccfnepa</padig:setInt>
        <padig:setInt string="Lackawanna Valley Digital Archives">papd_pscrl-fsplps</padig:setInt>
        <padig:setInt string="Lackawanna Valley Digital Archives">papd_pscrl-flmtcm</padig:setInt>
        <padig:setInt string="Lackawanna Valley Digital Archives">papd_pscrl-hspl</padig:setInt>
        <padig:setInt string="Lackawanna Valley Digital Archives">papd_pscrl-ndnepa</padig:setInt>
        <padig:setInt string="Lackawanna Valley Digital Archives">papd_pscrl-naap</padig:setInt>
        <padig:setInt string="Lackawanna Valley Digital Archives">papd_pscrl-ootw</padig:setInt>
        <padig:setInt string="Lackawanna Valley Digital Archives">papd_pscrl-scw</padig:setInt>
        <padig:setInt string="Lackawanna Valley Digital Archives">papd_pscrl-socmc</padig:setInt>
    </xsl:param>

    <!-- POWER photos and docs collecton name lookup -->
    <xsl:param name="powerSetSpecList">
        <padig:set string="Abington Township Public Library - Abington High School Yearbooks">papd_paflp-ahsyc</padig:set>
        <padig:set string="Academy of Natural Sciences of Drexel University - Historic Trees of the Delaware Valley and Maryland Photographs">papd_adrex-htotdvamp</padig:set>
        <padig:set string="Academy of Natural Sciences of Drexel University - Lucy Say Illustrations">papd_adrex-lsi</padig:set>
        <padig:set string="Albright College - Central Pennsylvania College Photos">papd_cpaphoto</padig:set>
        <padig:set string="Albright College - Evangelical Church Historic Lantern Slides">papd_churchslide</padig:set>
        <padig:set string="Albright College - Myerstown Photos">papd_myrsphoto</padig:set>
        <padig:set string="Albright College - Schuylkill Seminary Photos">papd_sklsemphoto</padig:set>
        <padig:set string="Albright College - The Seminary Guard Newspaper">papd_aalbcsemgu_96_2_4</padig:set>
        <padig:set string="Albright College - The Seminary Guard Newspaper">papd_aalbcsemgu_96</padig:set>
        <padig:set string="Albright College - The Seminary Guard Newspaper">papd_aalbcsemgu</padig:set>
        <padig:set string="Altoona Area Public Library - Altoona Area School District History">papd_palap-aasdh</padig:set>
        <padig:set string="Altoona Area Public Library - Architecture: Practical and Theoretical">papd_palap-apt</padig:set>
        <padig:set string="Altoona Area Public Library - Blair County Historic Reports">papd_palap-bchr</padig:set>
        <padig:set string="Altoona Area Public Library - Blair County Oral Histories">papd_palap-bcoh</padig:set>
        <padig:set string="Altoona Area Public Library - History Photographs">papd_palap-hp</padig:set>
        <padig:set string="Altoona Area Public Library - The Great Flood of 1977">papd_palap-gf1977</padig:set>
        <padig:set string="Battle of Homestead Foundation - Charles McCollester Collection">papd_sbhfa-cmc</padig:set>
        <padig:set string="Battle of Homestead Foundation - Mark Fallon Collection">papd_sbhfa-mfc</padig:set>
        <padig:set string="Battle of Homestead Foundation - Mike Stout Collection">papd_sbhfa-msc</padig:set>
        <padig:set string="Bedford County Library - Winona Garbrick">papd_pbecf-wg</padig:set>
        <padig:set string="Bellwood-Antis Public Library - Bellwood Bulletin Newspaper">papd_pbapl-bb</padig:set>
        <padig:set string="Bethlehem Area Public Library - Greene-Dreher Historical Society - Hopedale Moravian Church Pastors' Letters 1836-1878">papd_pbeap-gdhshmcpl</padig:set>
        <padig:set string="Benjamin Franklin Jones Memorial Library - Selected Newspaper Clippings Aliquippa Area">papd_pbfja-sncaa</padig:set>
        <padig:set string="Benjamin Franklin Jones Memorial Library - Selected Photographs Aliquippa Area">papd_pbfja-spaa</padig:set>
        <padig:set string="Bernville Area Community Library - Tulpehocken High School Yearbooks">papd_pbeac-thsy</padig:set>
        <padig:set string="Boyertown Area Senior High School - Boyertown School News">papd_kboyh-bsn</padig:set>
        <padig:set string="Braddock Carnegie Library Association - Braddock Area Year Books">papd_pbcal-bayb</padig:set>
        <padig:set string="Byzantine Catholic Seminary Library - Eastern Christian Liturgical Music">papd_abyzc-eclm</padig:set>
        <padig:set string="Byzantine Catholic Seminary Library - Prostopinije (Slavic Plain Chant)">papd_abyzc-pspc</padig:set>
        <padig:set string="C. C. Mellor Memorial Library - History of Edgewood Schools">papd_pccmm-hoes</padig:set>
        <padig:set string="C. C. Mellor Memorial Library - The History of the Borough of Edgewood">papd_pccmm-ccmml</padig:set>
        <padig:set string="Cambria County Library - Johnstown, PA History Books">papd_pcccp-books</padig:set>
        <padig:set string="Cambria County Library - Johnstown, PA Postcards">papd_pcccp-post</padig:set>
        <padig:set string="Cambria County Library - Johnstown Area Yearbooks">papd_pcccp-jay</padig:set>
        <padig:set string="Carnegie Library of Homestead - The Homestead Daily News, News Messenger, &amp; Daily Messenger 1897-1979">papd_pcalh-hdnnmdm</padig:set>
        <padig:set string="Carnegie Library of Homestead - Homestead Newspaper Collection 1881-1979">papd_pcalh-hnc1881</padig:set>
        <padig:set string="Carnegie Library of Pittsburgh - American Marketplace">papd_pcalo-amc</padig:set>
        <padig:set string="Carnegie Library of Pittsburgh - Industry, Mining, &amp; Technology Journals">papd_pcalo-imtj</padig:set>
        <padig:set string="Carnegie Library of Pittsburgh - Iron &amp; Steel Photographic Collection">papd_pcalo-ispc</padig:set>
        <padig:set string="Carnegie Library of Pittsburgh - Pittsburgh Iron &amp; Steel Heritage">papd_pcalo-ishc</padig:set>
        <padig:set string="Carnegie Library of Pittsburgh - The Builder">papd_pcalo-build2</padig:set>
        <padig:set string="Carnegie Mellon University - Andrew Carnegie Online Archives">papd_acamu-acarc</padig:set>
        <padig:set string="Carnegie Mellon University - Historic Images">papd_acamu-cmuhi</padig:set>
        <padig:set string="Centre County Library and Historical Museum - Autobiography of Colonel Samuel Miles">papd_pcecl-aocsm</padig:set>
        <padig:set string="Centre County Library and Historical Museum - Bellefonte Governors' Papers">papd_pcecl-bgp</padig:set>
        <padig:set string="Centre County Library and Historical Museum - Centre County Greg Post No. 95 GAR Veteran Books">papd_pcecl-mhmgarp95b</padig:set>
        <padig:set string="Centre County Library and Historical Museum - Centre County School Class Photographs">papd_pcecl-ccscp</padig:set>
        <padig:set string="Centre County Library and Historical Museum - John Blair Linn Photo Album">papd_pcecl-jblpa</padig:set>
        <padig:set string="Centre County Library and Historical Museum - John Blair Linn's Trip to the Gettysburg Battlefield">papd_pcecl-jbltttgb</padig:set>
        <padig:set string="Centre County Library and Historical Museum - Keller Letters">papd_pcecl-kl</padig:set>
        <padig:set string="Centre County Library and Historical Museum - Letters and Notes of Colonel Samuel Miles">papd_pcecl-lanocsm</padig:set>
        <padig:set string="Centre County Library and Historical Museum - Mary E. D. Wilson Composition Collection">papd_pcecl-medwcc</padig:set>
        <padig:set string="Centre County Library and Historical Museum - Miles-Potter-Humes House">papd_pcecl-mphh</padig:set>
        <padig:set string="Centre County Library and Historical Museum - P. Benner Wilson Letters">papd_pcecl-pbwl</padig:set>
        <padig:set string="Cheltenham Township Library System - Cheltenham Historical Photograph Collection">papd_pglfl-chpc</padig:set>
        <padig:set string="Cheltenham Township Library System - Cheltenham Township Properties">papd_pglfl-cthp</padig:set>
        <padig:set string="Cheltenham Township Library System - Historic La Mott/ Cheltenham Township Community">papd_pglfl-hlmctc</padig:set>
        <padig:set string="Chester County History Center - Abigail Speakman Diary Collection">papd_scchc-asdc</padig:set>
        <padig:set string="Chester County History Center - Acoccidologists Travel Diary Collection">papd_scchc-atdc</padig:set>
        <padig:set string="Chester County History Center - A. D. Sharples Letterpress Book Collection">papd_scchc-adslbc</padig:set>
        <padig:set string="Chester County History Center - Charles J. Pennock Papers">papd_scchc-cjpp</padig:set>
        <padig:set string="Chester County History Center - Chester County Archives and Record Services - Chester County Board of Relief">papd_scchc-ccbof</padig:set>
        <padig:set string="Chester County History Center - David Evans Collection">papd_scchc-dec</padig:set>
        <padig:set string="Chester County History Center - Edmund D. Cleaver Diary Collection">papd_scchc-edcdc</padig:set>
        <padig:set string="Chester County History Center - Elizabeth Broomell Passmore Diary Collection">papd_scchc-ebpdc</padig:set>
        <padig:set string="Chester County History Center - Ennion Cook Account Book Collection">papd_scchc-ecabc</padig:set>
        <padig:set string="Chester County History Center - Halliday Jackson Collection">papd_scchc-hjc</padig:set>
        <padig:set string="Chester County History Center - Jacob M. March Diary Collection">papd_scchc-jmmdc</padig:set>
        <padig:set string="Chester County History Center - Jean Kane Foulke Papers">papd_scchc-jkfp</padig:set>
        <padig:set string="Chester County History Center - John Churchman Papers: Early Land Grants and Surveys in Chester County, Pa. (Nottingham Lots)">papd_scchc-jcpelgascc</padig:set>
        <padig:set string="Chester County History Center - John Hill Brinton Reminiscences Collection">papd_scchc-jhbrc</padig:set>
        <padig:set string="Chester County History Center - John Townsend Diary Collection">papd_scchc-jtdc</padig:set>
        <padig:set string="Chester County History Center - Lewis White Williams Diary Collection">papd_scchc-lwwdc</padig:set>
        <padig:set string="Chester County History Center - Liberty Cornet Band Minutes and Membership Book">papd_scchc-lcbmamb</padig:set>
        <padig:set string="Chester County History Center - Mary Eliza Brinton Hopkins Diary Collection">papd_scchc-mebhdc</padig:set>
        <padig:set string="Chester County History Center - Phebe Ann Sharpless Diary Collection">papd_scchc-pasdc</padig:set>
        <padig:set string="Chester County History Center - Rebecca Townsend Brown Diary Collection">papd_scchc-rtbdc</padig:set>
        <padig:set string="Chester County History Center - Sheeder Family Account Books and Diaries">papd_scchc-sfabad</padig:set>
        <padig:set string="Chester County History Center - Timothy Kirk Memorandum Book Collection">papd_scchc-tkmbc</padig:set>
        <padig:set string="Chester County History Center - Walter Finney Diary Collection">papd_scchc-wfdc</padig:set>
        <padig:set string="Chester County History Center - William Darlington Letterpress Copybook">papd_scchc-wdlc</padig:set>
        <padig:set string="Chester County History Center - William H. Brown Diary Collection">papd_scchc-whbdc</padig:set>
        <padig:set string="Chester County History Center - William Riley Blakeslee Diary Collection">papd_scchc-wrbdc</padig:set>
        <padig:set string="Chester County History Center - William W. Heed Diary Collection">papd_scchc-wwhdc</padig:set>
        <padig:set string="Chester County History Center - Women's Suffrage and Civil Rights Collection">papd_scchc-wsacrc</padig:set>
        <padig:set string="Chester County Library &amp; District - Northern Chester County Historic Photographs">papd_pcccl-ncchp</padig:set>
        <padig:set string="Clarion Free Library - Mary Hamilton Holiday Cards">papd_pclfl-mhhc</padig:set>
        <padig:set string="Clarion Free Library - World War I">papd_pclfl-wwi</padig:set>
        <padig:set string="College of Physicians of Philadelphia - Colonial Formularies">papd_cppmss</padig:set>
        <padig:set string="Conshohocken Free Library - Conshohocken Town Council Minutes">papd_pcofl-mtc1</padig:set>
        <padig:set string="Conshohocken Free Library - The Recorder Newspaper 1879-1964">papd_pcofl-creco</padig:set>
        <padig:set string="Cooper-Siegel Community Library - Fox Chapel Area High School Renard Yearbooks">papd_plawm-fcahsry</padig:set>
        <padig:set string="Cooper-Siegel Community Library - Fox Chapel Area Historical Materials">papd_plawm-fcahm</padig:set>
        <padig:set string="Crawford County Federated Library System - Meadville Local History">papd_pmeplmlhc</padig:set>
        <padig:set string="DeSales University - Bishop McShea Archives">papd_adesu-bmcsa</padig:set>
        <padig:set string="DeSales University - St. Francis de Sales">papd_adesu-sfdes</padig:set>
        <padig:set string="Elizabethtown College - Anna V. Blough Missionary Letters and Diaries from China">papd_aeliz-lttrs</padig:set>
        <padig:set string="Elizabethtown College - Church of the Brethren Photographs">papd_aeliz-cbpc</padig:set>
        <padig:set string="Elizabethtown College - Historic Images">papd_aeliz-hi</padig:set>
        <padig:set string="Elizabethtown College - Peace Pamphlets">papd_aeliz-pp</padig:set>
        <padig:set string="Elizabethtown College - Teachers for West Africa Program Images">papd_aeliz-tfwapi</padig:set>
        <padig:set string="Erie County Public Library - Erie County COVID-19 Oral Histories">papd_percp-ecc19oh</padig:set>
        <padig:set string="Erie County Public Library - Erie County Maps">papd_percp-ecm</padig:set>
        <padig:set string="Erie County Public Library - Erie County Yearbooks">papd_percp-ecy</padig:set>
        <padig:set string="Erie County Public Library - Erie Gay News">papd_percp-egn</padig:set>
        <padig:set string="Erie County Public Library - Erie Gazette 1820-1864">papd_percp-egaz</padig:set>
        <padig:set string="Erie County Public Library - Erie Public Library Reports">papd_percp-eplr</padig:set>
        <padig:set string="Erie County Public Library - Grand Army of the Republic: Personal War Sketches of the Members of Strong Vincent Post No. 67">papd_percp-ecplgar</padig:set>
        <padig:set string="Friends Central School - Early Photographs">papd_kfces-photo</padig:set>
        <padig:set string="German Society of Pennsylvania - Deutsche Ansiedelungs-Gesellschaft zu Philadelphia (German Settlement Society of Philadelphia) records">papd_sgsop-daggssr</padig:set>
        <padig:set string="German Society of Pennsylvania - German Society Agentur">papd_sgsop-gsa</padig:set>
        <padig:set string="German Society of Pennsylvania - Henry Keppele Records">papd_sgsop-hkr</padig:set>
        <padig:set string="German Society of Pennsylvania - Henry Melchior Muhlenberg Papers, 1771-1786">papd_sgsop-hmmp1771</padig:set>
        <padig:set string="German Society of Pennsylvania - John F. Ballier Civil War Journal">papd_sgsop-jfbcwj</padig:set>
        <padig:set string="German Society of Pennsylvania - Philadelphia Demokrat">papd_sgsop-gsppd</padig:set>
        <padig:set string="German Society of Pennsylvania - Philadelphia Demokrat (1838)">papd_sgsop-gsppd1838</padig:set>
        <padig:set string="German Society of Pennsylvania - Singing Societies Collection">papd_sgsop-ssc</padig:set>
        <padig:set string="German Society of Pennsylvania - Women's Auxiliary of the German Society of Pennsylvania">papd_sgsop-wagsp</padig:set>
        <padig:set string="Germantown Historical Society/ Historic Germantown - Pamphlet Box Collection/ Pennsylvania School for the Deaf">papd_sgehs-pbcpsftd</padig:set>
        <padig:set string="Germantown Historical Society/ Historic Germantown - Pamphlet Boxes African-American History Collection">papd_sgehs-pbaahc</padig:set>
        <padig:set string="Germantown Historical Society/ Historic Germantown - Pamphlet Boxes Welfare History Collection">papd_sgehs-pbwhc</padig:set>
        <padig:set string="Heinz History Center - Buhl Foundation Photographs">papd_shswp-bfp</padig:set>
        <padig:set string="Hempfield High School (Landisville PA) - The Flash - Hempfield High School Newspaper">papd_khmph-fhhsn</padig:set>
        <padig:set string="Henderson High School - B. Reed Henderson High School Collection">papd_khendhscol</padig:set>
        <padig:set string="Historical Society of Montgomery County - African American History Collection">papd_shsmc-aahc</padig:set>
        <padig:set string="Historical Society of Montgomery County - Historic Photographs of Norristown">papd_shsmc-hpn</padig:set>
        <padig:set string="Indiana University of Pennsylvania - Indiana, Pennsylvania in the Civil War">papd_aiupa-cw</padig:set>
        <padig:set string="Indiana University of Pennsylvania - Indiana University of Pennsylvania (IUP) Collection">papd_aiupa-iuopc</padig:set>
        <padig:set string="James V. Brown Library - Historic Documents">papd_pjvbl-docs</padig:set>
        <padig:set string="James V. Brown Library - Lycoming County Digital Photo Archive">papd_pjvbl-archi</padig:set>
        <padig:set string="Jersey Shore Public Library - The Jersey Shore Historical Society - The Jersey Shore Historical Society Photographs">papd_pjspl-jshsp</padig:set>
        <padig:set string="Julia R. Masterman School - Julia R. Masterman School Yearbooks">papd_0001k-jrmsy</padig:set>
        <padig:set string="Juniata College - Huntingdon County Historical Newspapers">papd_ajuncnews</padig:set>
        <padig:set string="Keystone College - 1868 to present">papd_akeys-1868</padig:set>
        <padig:set string="Keystone College - Christy Mathewson">papd_akeyscmath</padig:set>
        <padig:set string="Keystone College - Local History">papd_akeyslhist</padig:set>
        <padig:set string="Kiski School - Digital Archive">papd_kthks-tksc_266_2_1</padig:set>
        <padig:set string="Kiski School - Digital Archive">papd_kthks-tksc_266</padig:set>
        <padig:set string="Kiski School - Digital Archive">papd_kthks-tksc</padig:set>
        <padig:set string="Kittanning Public Library - Kittanning's Natural Disasters">papd_kkifl-knd</padig:set>
        <padig:set string="Knoxville Public Library - Knoxville Pennsylvania 1880-1920">papd_pkvpl-knpe</padig:set>
        <padig:set string="Lancaster Public Library - Local History">papd_placl-lhist</padig:set>
        <padig:set string="Lancaster Public Library - Yearbooks">papd_placl-ybook</padig:set>
        <padig:set string="LancasterHistory - City Directories 1843-1900">papd_slchs-cd01</padig:set>
        <padig:set string="LancasterHistory - City Directories 1901-1914">papd_slchs-cd02</padig:set>
        <padig:set string="LancasterHistory - City Directories 1914-1922">papd_slchs-cd03</padig:set>
        <padig:set string="LancasterHistory - Lancaster Examiner and Herald Newspaper 1834-1854">papd_slchs-leh01</padig:set>
        <padig:set string="LancasterHistory - Lancaster Examiner and Herald Newspaper 1855-1872">papd_slchs-leh02</padig:set>
        <padig:set string="LancasterHistory - Lititz Newspapers">papd_slchs-lnp1</padig:set>
        <padig:set string="LancasterHistory - New Holland Clarion Newspaper 1873-1890">papd_nhclar01</padig:set>
        <padig:set string="LancasterHistory - New Holland Clarion Newspaper 1891-1910">papd_nhclar02</padig:set>
        <padig:set string="LancasterHistory - New Holland Clarion Newspaper 1911-1950">papd_nhclarion</padig:set>
        <padig:set string="Laughlin Memorial Library - Ambridge Historic Newspaper Collection">papd_plamf-ahnc</padig:set>
        <padig:set string="Ligonier Valley Library - Ligonier Valley Library Yearbook Collection">papd_plivl-lvlyc</padig:set>
        <padig:set string="Lock Haven University - 1877-2008">papd_alhupviscro</padig:set>
        <padig:set string="Lock Haven University - Wrestling Program">papd_alhupwrest</padig:set>
        <padig:set string="Lycoming College - Alumni Magazine of Lycoming College">papd_alycc-almag</padig:set>
        <padig:set string="Lycoming College - Historical Documents">papd_aalyc-hdocs2</padig:set>
        <padig:set string="Lycoming College - Lycoming College Campus - Past and Present">papd_lyc-5</padig:set>
        <padig:set string="Lycoming College - Lycoming College">papd_lyc-4</padig:set>
        <padig:set string="Lycoming College - Lycoming County Women's History">papd_alycc-wmhis_6567</padig:set>
        <padig:set string="Lycoming College - Lycoming County Women's History">papd_alycc-wmhis_7146</padig:set>
        <padig:set string="Lycoming College - Lycoming County Women's History">papd_alycc-wmhis_7510</padig:set>
        <padig:set string="Lycoming College - Lycoming County Women's History">papd_alycc-wmhis</padig:set>
        <padig:set string="Lycoming College - Moving Images of Lycoming College">papd_alycc-mvimg</padig:set>
        <padig:set string="Lycoming College - Student Newspapers, 1856-present">papd_lycnews</padig:set>
        <padig:set string="Lycoming College - Voices of Lycoming">papd_alycc-voice</padig:set>
        <padig:set string="Lycoming College - Williamsport Dickinson Seminary Junior College and College Preparatory School">papd_lyc-2</padig:set>
        <padig:set string="Lycoming College - Williamsport Dickinson Seminary of Lycoming College">papd_lyc-1</padig:set>
        <padig:set string="Lycoming College - Yearbooks of Lycoming College and Dickinson Seminary">papd_alycc-ybook</padig:set>
        <padig:set string="Manheim Township School District - Hi-Lite">papd_kmath-hl</padig:set>
        <padig:set string="Martinsburg Community Library - George Liebegott Genealogy Index">papd_pmbcl-li</padig:set>
        <padig:set string="Matthews Public Library - Fredericksburg, Pennsylvania Historic Images">papd_plecl-fphi</padig:set>
        <padig:set string="McBride Memorial Library - Berwick High School Yearbooks">papd_pbrpl-bhsyb</padig:set>
        <padig:set string="Memorial Library of Nazareth and Vicinity - Millgrove Schoolhouse">papd_pmeln-ms</padig:set>
        <padig:set string="Memorial Library of Nazareth and Vicinity - Nazareth Area World War II Scrapbook">papd_nazwwii</padig:set>
        <padig:set string="Memorial Library of Nazareth and Vicinity - Nazareth Day at the 1939 New York World's Fair">papd_pmeln-nd1939nywf</padig:set>
        <padig:set string="Memorial Library of Nazareth and Vicinity - Nazareth Item Newspaper 1891-1975">papd_naz_item</padig:set>
        <padig:set string="Memorial Library of Nazareth and Vicinity - The N.H.S. Chronicle">papd_pmeln-nhsc</padig:set>
        <padig:set string="Mengle Memorial Library - The Punxsutawney Spirit Newspaper">papd_pmeml-psprt</padig:set>
        <padig:set string="Meyersdale Public Library - 1998 Southern Somerset County Tornadoes Oral Histories">papd_pmeye-1998ssctoh</padig:set>
        <padig:set string="Meyersdale Public Library - African American Burials in Somerset County">papd_pmeye-aabisc</padig:set>
        <padig:set string="Meyersdale Public Library - Captain William (Will) Lewis Judy">papd_pmeye-cwlj</padig:set>
        <padig:set string="Meyersdale Public Library - From Dale City to Meyersdale">papd_pmeye-fdctm</padig:set>
        <padig:set string="Meyersdale Public Library - Garrett School Memorabilia">papd_pmeye-gsm</padig:set>
        <padig:set string="Meyersdale Public Library - Maple Valley Park and Pool">papd_pmeye-mvpp</padig:set>
        <padig:set string="Meyersdale Public Library - Meyersdale Area High School Yearbooks">papd_pmeye-mahsy</padig:set>
        <padig:set string="Meyersdale Public Library - Meyersdale Commercial Newspaper">papd_pmeye-mcn</padig:set>
        <padig:set string="Meyersdale Public Library - Meyersdale Community Hospital">papd_pmeye-mch</padig:set>
        <padig:set string="Meyersdale Public Library - Meyersdale Kelly Korps">papd_pmeye-mkk</padig:set>
        <padig:set string="Meyersdale Public Library - Meyersdale Volunteer Fire Department History">papd_pmeye-mvfdh</padig:set>
        <padig:set string="Meyersdale Public Library - Old-Time Meyersdale Photographs">papd_pmeye-otmp</padig:set>
        <padig:set string="Meyersdale Public Library - Pennsylvania Maple Festival Memories">papd_pmeye-pmfm</padig:set>
        <padig:set string="Meyersdale Public Library - Photographs">papd_pmeye-photo</padig:set>
        <padig:set string="Meyersdale Public Library - Railway Accidents">papd_pmeye-ra</padig:set>
        <padig:set string="Meyersdale Public Library - Red and Black Student Paper">papd_pmeye-rabsp</padig:set>
        <padig:set string="Meyersdale Public Library - Rockwood Area Historical &amp; Genealogical Society - Casselman Village Area">papd_pmeye-cva</padig:set>
        <padig:set string="Meyersdale Public Library - Rockwood Area Historical &amp; Genealogical Society - Rockwood Borough History">papd_pmeye-rbh</padig:set>
        <padig:set string="Meyersdale Public Library - Rural African Americans of the Allegheny Mountains">papd_pmeye-raaotam</padig:set>
        <padig:set string="Meyersdale Public Library - Springs Historical Society - Johnston Bender Family Collection">papd_pmeye-jbfc</padig:set>
        <padig:set string="Meyersdale Public Library - Springs Historical Society - Miller Machine">papd_pmeye-mm</padig:set>
        <padig:set string="Meyersdale Public Library - Springs Historical Society - Wagner Collection">papd_pmeye-wc</padig:set>
        <padig:set string="Meyersdale Public Library - The History Behind the Meyersdale Public Library">papd_pmeye-hbtmpl</padig:set>
        <padig:set string="Meyersdale Public Library - The Meyersdale Republican Newspaper">papd_pmeye-mrn</padig:set>
        <padig:set string="Meyersdale Public Library - The Somerset County Times (Rockwood, Pa.) Newspaper">papd_pmeye-sctrpn</padig:set>
        <padig:set string="Meyersdale Public Library - William Henry Welfley Scrapbook Collection">papd_pmeye-whwsc</padig:set>
        <padig:set string="Milanof-Schock Public Library - Donegal High School Yearbooks">papd_pmisl-dhsy</padig:set>
        <padig:set string="Milanof-Schock Public Library - East Donegal Township High School Yearbooks">papd_pmisl-edthsy</padig:set>
        <padig:set string="Milanof-Schock Public Library - Mount Joy High School Yearbooks">papd_pmisl-mjhsy</padig:set>
        <padig:set string="Milton Hershey School - Hershey Community Archives - Hotel Hershey Highlights">papd_kmheh-hcahhh</padig:set>
        <padig:set string="Milton Hershey School - Hershey News Newspaper 1953-1964">papd_kmheh-hn</padig:set>
        <padig:set string="Milton Hershey School - The Hershey Press Newspaper 1909-1926">papd_kmheh-thpc</padig:set>
        <padig:set string="Milton Hershey School - The Hershey Press Newspaper 1909-1926">papd_kmheh-thpc_6507</padig:set>
        <padig:set string="Milton Hershey School - The Hershey Press Newspaper 1909-1926">papd_kmheh-thpc_6507_2_1</padig:set>
        <padig:set string="Milton Hershey School - The Hershey Press Newspaper 1909-1926">papd_kmheh-thpc_6507_2_2</padig:set>
        <padig:set string="Monroeville Public Library - Allegheny County Yearbooks">papd_pmonr-acy</padig:set>
        <padig:set string="Montgomery County Community College - Betzwood Studios">papd_amccc-betz</padig:set>
        <padig:set string="Montgomery County Community College - The Montgazette Newspaper 1967-2017">papd_amccc-mgztt</padig:set>
        <padig:set string="Montgomery County Community College - Yearbooks">papd_amccc-yb</padig:set>
        <padig:set string="New Castle Public Library - 100th Anniversary">papd_pncpl-100</padig:set>
        <padig:set string="New Castle Public Library - Cascade Park">papd_pncpl-cp</padig:set>
        <padig:set string="New Castle Public Library - History Room Documents">papd_pncpl-hrd</padig:set>
        <padig:set string="New Castle Public Library - Laurel High School Yearbooks">papd_pncpl-lhsy</padig:set>
        <padig:set string="New Castle Public Library - Lawrence County Area Vocational Technical School Yearbooks">papd_pncpl-lcatsy</padig:set>
        <padig:set string="New Castle Public Library - Mohawk Area High School Yearbooks">papd_pncpl-mahsy</padig:set>
        <padig:set string="New Castle Public Library - Neshannock Township High School Yearbooks">papd_pncpl-nthsy</padig:set>
        <padig:set string="New Castle Public Library - New Castle Directories 1872-1899">papd_pncpl-cdr01</padig:set>
        <padig:set string="New Castle Public Library - New Castle Directories 1900-1910">papd_pncpl-cdr02</padig:set>
        <padig:set string="New Castle Public Library - New Castle Directories 1911-1918">papd_pncpl-cdr03</padig:set>
        <padig:set string="New Castle Public Library - New Castle Directories 1921-1928">papd_pncpl-cdr04</padig:set>
        <padig:set string="New Castle Public Library - New Castle High School Yearbooks">papd_pncpl-nchsy</padig:set>
        <padig:set string="New Castle Public Library - Shenango Area High School Yearbooks">papd_pncpl-sahsy</padig:set>
        <padig:set string="New Castle Public Library - Union Township High School Yearbooks">papd_pncpl-uthsyb</padig:set>
        <padig:set string="New Castle Public Library - Wilmington Area High School Yearbooks">papd_pncpl-wahsy</padig:set>
        <padig:set string="New Cumberland Public Library - Around Town">papd_pnecp-at</padig:set>
        <padig:set string="New Cumberland Public Library - Churches of New Cumberland">papd_pnecp-conc</padig:set>
        <padig:set string="New Cumberland Public Library - Groups and Organizations of New Cumberland">papd_pnecp-gaoonc</padig:set>
        <padig:set string="New Cumberland Public Library - Local News">papd_pnecp-ln</padig:set>
        <padig:set string="New Cumberland Public Library - NC Hi Magazines">papd_pnecp-nchm</padig:set>
        <padig:set string="New Cumberland Public Library - New Cumberland Flood of 1936">papd_pnecp-ncf1936</padig:set>
        <padig:set string="New Cumberland Public Library - New Cumberland Public Library Collection">papd_pnecp-ncplc</padig:set>
        <padig:set string="New Cumberland Public Library - New Cumberland Town Celebrations">papd_pnecp-nctc</padig:set>
        <padig:set string="New Cumberland Public Library - Roland Benjamin collection">papd_pnecp-rbc</padig:set>
        <padig:set string="New Cumberland Public Library - Schools of New Cumberland">papd_pnecp-snc</padig:set>
        <padig:set string="New Cumberland Public Library - Scrapbooks and Memorabilia">papd_pnecp-sam</padig:set>
        <padig:set string="New Cumberland Public Library - William D. Bailey 1863 Civil War Diary">papd_pnecp-wdb1862</padig:set>
        <padig:set string="Old Economy Village - Archives">papd_solev-arch</padig:set>
        <padig:set string="Osterhout Free Library - Wilkes-Barre Sunday Independent Newspaper 1915-1958">papd_wbsunind</padig:set>
        <padig:set string="Pennsylvania College of Technology - Williamsport Area Community College - 1960s">papd_apact-wacc1960</padig:set>
        <padig:set string="Pennsylvania College of Technology - Williamsport Technical Institute">papd_willtech</padig:set>
        <padig:set string="Pennsylvania Geological Survey - Historical Photographs">papd_spgsl-photo</padig:set>
        <padig:set string="Pennsylvania Geological Survey - Hurricane Agnes Flood Photographs">papd_spgsl-hafp</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - American Association of University Women - Johnstown Branch">papd_acacc-aauwjb</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - Bailey Collection">papd_acacc-bailey</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - Beaverdale Collection">papd_acacc-bdale</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - Beth Sholom Synagogue">papd_acacc-bss</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - Business Licenses Collection">papd_acacc-blc</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - Cambria City Church Project">papd_acacc-cccp</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - Cambria Civil War 150">papd_acacc-cw</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - Cambria Co. Immigration Declarations">papd_acacc-ccip</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - Cambria County Education Collection">papd_acacc-ccec</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - Cambria Memory Project">papd_acacc-memor</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - Conemaugh School of Nursing">papd_acacc-cson</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - Cresson Sanatorium">papd_acacc-cs</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - Dale Borough">papd_acacc-db</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - Johnstown Area Fire Department Collection">papd_acacc-jafd</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - Johnstown Art League">papd_acacc-jal</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - Johnstown Steel Industry Collection">papd_acacc-jsic</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - Klahre Collection">papd_acacc-klahre</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - Northern Cambria Collection">papd_acacc-noca</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - Suppes Collection">papd_acacc-sc</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - The Johnstown Flood of 1889">papd_acacc-jtf</padig:set>
        <padig:set string="Pennsylvania Highlands Community College - Wilmore Collection">papd_acacc-wilmore</padig:set>
        <padig:set string="Pennsylvania Horticultural Society - Ida W. Pritchett Photograph Collection">papd_spahs-iwppc</padig:set>
        <padig:set string="Pennsylvania Horticultural Society - James Lawrence Dillon Lantern Slide Collection">papd_spahs-jldlsc</padig:set>
        <padig:set string="Pennsylvania Horticultural Society - Jay V. Hare Lantern Slide Collection">papd_spahs-jvhlsc</padig:set>
        <padig:set string="Pennsylvania Horticultural Society - Joseph Ascenzi Lantern Slide Collection">papd_spahs-jalsc</padig:set>
        <padig:set string="Pennsylvania Horticultural Society - Louise Bush-Brown Image Collection">papd_spahs-lbbic</padig:set>
        <padig:set string="Pennsylvania Horticultural Society - Philadelphia Flower Show">papd_spahs-pfsc</padig:set>
        <padig:set string="Pennsylvania Horticultural Society - Philadelphia Garden Photographs, 1900-1940: 1. Garden Club of Philadelphia">papd_spahs-pgpgcp</padig:set>
        <padig:set string="Pennsylvania Horticultural Society - Philadelphia Garden Photographs, 1900-1940: 2. John C. Wister Collection">papd_spahs-pgp1940</padig:set>
        <padig:set string="Pennsylvania Horticultural Society - Philadelphia Garden Photographs, 1900-1940: 3. PHS Collection Portfolios">papd_spahs-pgpphscp</padig:set>
        <padig:set string="Pennsylvania Horticultural Society - PHS Archives Digital Image Collection">papd_spahs-padic</padig:set>
        <padig:set string="Pennsylvania School for the Deaf - Mount Airy Campus">papd_kpsfd-mac</padig:set>
        <padig:set string="Pennsylvania School for the Deaf - Pennsylvania School for the Deaf Yearbooks">papd_kpsfd-psftdy</padig:set>
        <padig:set string="Peters Township Public Library - Historic Images and Documents Collection">papd_ppetl-hidc</padig:set>
        <padig:set string="Peters Township Public Library - Life in Peters Township: An Oral History Project">papd_ppetl-lipt</padig:set>
        <padig:set string="Peters Township Public Library - Peters Township Chamber of Commerce business guides and community directories">papd_ppetl-ptcocbgacd</padig:set>
        <padig:set string="Peters Township Public Library - Peters Township High School Yearbooks">papd_ppetl-pthsy</padig:set>
        <padig:set string="Peters Township Public Library - Peters Township News 1958-1959">papd_ppetl-ptn1958</padig:set>
        <padig:set string="Peters Township Public Library - Peters Township News Progress 1959-1970">papd_ppetl-ptnp1959</padig:set>
        <padig:set string="Peters Township Public Library - The Commerce News 1955-1958">papd_ppetl-tcn1955</padig:set>
        <padig:set string="Pottsville Free Public Library - Schuylkill County History">papd_ppofp-sch</padig:set>
        <padig:set string="Pottsville Free Public Library - Schuylkill County Photographs">papd_ppofp-scp</padig:set>
        <padig:set string="Reading Area Community College - Reading Area Community College - Yearbook Collection">papd_aracc-ybc</padig:set>
        <padig:set string="Reading Area Community College - The Schuylkill Navigation System">papd_aracc-sns</padig:set>
        <padig:set string="Reading Area Community College - Wes Fisher Piano Sheet Music Collection">papd_aracc-wfpsmc</padig:set>
        <padig:set string="Reading Public Library - Berks County Postcards">papd_prepl-brcpc</padig:set>
        <padig:set string="Reading Public Library - Berks County Yearbooks">papd_prepl-brcyb</padig:set>
        <padig:set string="Ridley Park Public Library - Ridley Park High School Yearbooks">papd_pripp-rphsy</padig:set>
        <padig:set string="Ridley Park Public Library - Ye Ridlyan">papd_pripp-yr</padig:set>
        <padig:set string="Saint Francis University - Student Newspapers 1927-2006">papd_astfr-ysnmc</padig:set>
        <padig:set string="Saint Francis University Yearbooks 1942-2016">papd_astfr-yearbks</padig:set>
        <padig:set string="Saint Joseph's University - Beltran Kropp Papers">papd_astju-bkp</padig:set>
        <padig:set string="Saint Joseph's University - Marvin Samson Museum for the History of Pharmacy - Philadelphia College of Pharmacy History">papd_astju-mschppcph</padig:set>
        <padig:set string="Saint Joseph's University - Marvin Samson Museum for the History of Pharmacy – Philadelphiana">papd_astju-msmfthopp</padig:set>
        <padig:set string="Saint Joseph's University - The Hawk">papd_astju-hawk1931</padig:set>
        <padig:set string="Schwenkfelder Library &amp; Heritage Center - Amos A. Yeakel Civil War Diary">papd_sslhc-aaycwd</padig:set>
        <padig:set string="Schwenkfelder Library &amp; Heritage Center - Rosina Heydrich's Midwifery Manual and Ledger, 1770-1819">papd_sslch-sdsa</padig:set>
        <padig:set string="Schwenkfelder Library &amp; Heritage Center - Schwenkfelder Library &amp; Heritage Center Cased Images Collection">papd_sslhc-slhccic</padig:set>
        <padig:set string="Schwenkfelder Library &amp; Heritage Center - The Christopher Saur, Jr. Diary and Account Book">papd_sslhc-csjdab</padig:set>
        <padig:set string="Scranton Public Library - Celebrating Our Towns: Lackawanna Co. Centennial Books and Community Histories">papd_pscrl-cot</padig:set>
        <padig:set string="Scranton Public Library - Century Club of Scranton">papd_pscrl-ccos</padig:set>
        <padig:set string="Scranton Public Library - Community and Church Cookbooks from Northeastern PA">papd_pscrl-cccfnepa</padig:set>
        <padig:set string="Scranton Public Library - Department of Public Safety Mug Shot Collection: 1903-1909">papd_pscrl-dpsmsc</padig:set>
        <padig:set string="Scranton Public Library - Friends of the Scranton Public Library Poetry Series">papd_pscrl-fsplps</padig:set>
        <padig:set string="Scranton Public Library - From Lace Makers to Coal Miners: Life in the Lackawanna Valley 1866-1920">papd_pscrl-flmtcm</padig:set>
        <padig:set string="Scranton Public Library - History of the Scranton Public Library">papd_pscrl-hspl</padig:set>
        <padig:set string="Scranton Public Library - Mid-Valley News">papd_pscrl-mvn</padig:set>
        <padig:set string="Scranton Public Library - Natural Disasters in NePA--Hurricane Diane">papd_pscrl-ndnepa</padig:set>
        <padig:set string="Scranton Public Library - Nay Aug Amusement Park--The Strohl Collection">papd_pscrl-naap</padig:set>
        <padig:set string="Scranton Public Library - Out of the Wilderness: The Industrialization and Development of the the Scranton Area 1850-1865">papd_pscrl-ootw</padig:set>
        <padig:set string="Scranton Public Library - Scranton Christmas Windows">papd_pscrl-scw</padig:set>
        <padig:set string="Scranton Public Library - The Story of the Community Medical Center">papd_pscrl-socmc</padig:set>
        <padig:set string="Sewickley Public Library - Historic Images and Documents">papd_psepl-hiad2</padig:set>
        <padig:set string="Sewickley Public Library - The Sewickley Herald Newspaper 1903-">papd_psepl-sh</padig:set>
        <padig:set string="Sewickley Township Public Library - Sewickley Area High School and Yough High School Yearbooks">papd_pswrc-sahsayhsy</padig:set>
        <padig:set string="Springside Chestnut Hill Academy - The Wissahickon Magazine Collection 1903-1931">papd_kspsl-wmc1903</padig:set>
        <padig:set string="St. Marys Public Library - The St. Marys Daily Press">papd_pstmp-smdp</padig:set>
        <padig:set string="Summerville Public Library - Summerville Story Project">papd_psupl-sp</padig:set>
        <padig:set string="Susquehanna University - 1858 to 1894">papd_asvbw150</padig:set>
        <padig:set string="Susquehanna University - 1895 to 1939">papd_asvbw95-39</padig:set>
        <padig:set string="Susquehanna University - 1940 to 1949">papd_asvbw40-49</padig:set>
        <padig:set string="Susquehanna University - 1950 to 1959">papd_asvbw50-59</padig:set>
        <padig:set string="Susquehanna University - 1960 to 1969">papd_asvbw60-69</padig:set>
        <padig:set string="Susquehanna University - 1970 to 1979">papd_asvbw70-79</padig:set>
        <padig:set string="Susquehanna University - 1980 to 1989">papd_asvbw80-89</padig:set>
        <padig:set string="Susquehanna University - 1990 to 1999">papd_asvbw90-99</padig:set>
        <padig:set string="Susquehanna University - 2000 to 2009">papd_asvbw00-09</padig:set>
        <padig:set string="Swarthmore Public Library - History of the Swarthmore Public Library Association">papd_pswpl-splh</padig:set>
        <padig:set string="Swarthmore Public Library - The Swarthmorean Newspaper 1914-2008">papd_pswpl-snppr</padig:set>
        <padig:set string="The Baldwin School - Blazers, Uniforms, Gowns">papd_kthbs-bug</padig:set>
        <padig:set string="The Baldwin School - Photos and Documents">papd_kthbs-arch</padig:set>
        <padig:set string="The Baldwin School - The Hourglass">papd_kthbs-hg</padig:set>
        <padig:set string="Ulysses Library Association - Phil Bennett Collection">papd_pulpl-pbc</padig:set>
        <padig:set string="Ulysses Library Association - Ulysses History">papd_pulpl-uh</padig:set>
        <padig:set string="Uniontown Public Library - Fayette County Iron Works Records">papd_punpl-fciwr</padig:set>
        <padig:set string="Uniontown Public Library - Photos of Fayette County, PA">papd_punpl-pofcp</padig:set>
        <padig:set string="Unionville High School - Unionville High School Scrapbooks">papd_kuvhs-uhss</padig:set>
        <padig:set string="Unionville High School - Unionville High School Yearbooks">papd_kuvhs-uhsy</padig:set>
        <padig:set string="United Lutheran Seminary Philadelphia - In Her Own Right: Anne E. Sanford Missionary Collection">papd_aulsp-ihoraes</padig:set>
        <padig:set string="United Lutheran Seminary Philadelphia - In Her Own Right: the Lutheran Deaconess Movement in the United States">papd_aulsp-ihorldm</padig:set>
        <padig:set string="United Lutheran Seminary Philadelphia - In Her Own Right: Women's Missionary Societies of the Lutheran Church">papd_aulsp-ihorwmslc</padig:set>
        <padig:set string="Upper Merion Area High School Library - Upper Merion Area High School Athletic Scrapbooks and Programs">papd_kupmh-umahsasap</padig:set>
        <padig:set string="Upper Merion Township Library - Upper Merion Area School District Yearbooks">papd_pupmt-sdybs</padig:set>
        <padig:set string="Upper Moreland Free Public Library - Upper Moreland High School Yearbooks">papd_pupmf-umhsy</padig:set>
        <padig:set string="Upper Moreland Free Public Library - Upper Moreland Oral Histories">papd_pupmf-umoh</padig:set>
        <padig:set string="Wagner Free Institute of Science - Engineering 1: The Materials of Engineering Construction">papd_swfis-e1mec</padig:set>
        <padig:set string="Wagner Free Institute of Science - Engineering 2: Civil Engineering Structures">papd_swfis-e2ces</padig:set>
        <padig:set string="Wagner Free Institute of Science - Manuscripts of Lectures on Conchology by William Wagner">papd_swfis-molocbww</padig:set>
        <padig:set string="Wagner Free Institute of Science - Manuscripts of Lectures on Mineralogy by William Wagner">papd_swfis-molombww</padig:set>
        <padig:set string="Warren Library Association - Historic Flood Control (1943)">papd_pwala-hstfl</padig:set>
        <padig:set string="Warren Library Association - Historic Photographs">papd_pwala-hstph</padig:set>
        <padig:set string="Warren Library Association - Kinzua Scrapbooks">papd_pwala-ks</padig:set>
        <padig:set string="Warren Library Association - The Allegheny Pilot">papd_pwala-alpil</padig:set>
        <padig:set string="Warren Library Association - The Carnival, First Presbyterian Church, 1899">papd_pwala-tcfpc</padig:set>
        <padig:set string="West Pittston Public Library - Pittston Gazette Newspaper 1850-1908">papd_pwepp-pgazz</padig:set>
        <padig:set string="Whitehall Township Public Library - Civil War Grave Registrations">papd_pwhtp-cwgr</padig:set>
        <padig:set string="Whitehall Township Public Library - Historical Books">papd_pwhtp-hb</padig:set>
        <padig:set string="Whitehall Township Public Library - Historical Photographs">papd_pwhtp-photo</padig:set>
        <padig:set string="Whitehall Township Public Library - Samuel and Rosa Kern Letters">papd_pwhtp-ltrs</padig:set>
        <padig:set string="Whitehall Township Public Library - Whitehall High School Yearbooks">papd_pwhtp-yb</padig:set>
        <padig:set string="Wilkes University - Hurricane Agnes Flood photographs">papd_pwufl-hafp</padig:set>
        <padig:set string="Wilkes University - Wilkes University Audio Recordings">papd_pwufl-wuar</padig:set>
        <padig:set string="Wilkes University - Wilkes University Film Footage">papd_pwufl-wuff</padig:set>
        <padig:set string="Wilkes University - Wilkes University Scrapbooks">papd_pwufl-wus</padig:set>
        <padig:set string="Williamson College of the Trades - Isaiah Van Sant Williamson History">papd_awsmt-ivswh</padig:set>
        <padig:set string="Williamson College of the Trades - Williamson Trade School History">papd_awsmt-wtsh</padig:set>
        <padig:set string="Wilson College - World War II">papd_awlsn-wwii</padig:set>
        <padig:set string="Wissahickon Valley Public Library - Ambler Gazette Newspaper">papd_wivp-gazett</padig:set>
        <padig:set string="Woodland Hills School District - Woodland Hills School District: Past and Present">papd_kwohh-whsdpap</padig:set>
    </xsl:param>
</xsl:stylesheet>
