version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.7.11
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: run tests
          command: make test-ci
