version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: run tests
          command: make test-ci
